//
//  store-data.swift
//  whoscheering
//
//  Created by Conrad on 5/25/15.
//  Copyright (c) 2015 Conrad. All rights reserved.
//

import Foundation


struct StoreData{
    //static let categories = ["NFL","NBA","MLB","NHL","MLS","EPL"]
    static let categories = details.keys.array
    
    //add IAP id for each team
    //add COLORS for each team
    //details.category.team.colors
    //details.category.team.name
    //details.category.team.appid
    //possibly simplify categories to be a function return, gather from the details array
    
    static let details = [
        "NFL" : ["Chargers","Broncos","Rams","Patriots", "ETC"],
        "NBA" : ["Bulls","Wizards","Raptors","Lakers", "ETC"],
        "MLB" : ["Padres","Angels","Dodgers","Yankees", "ETC"],
        "NHL" : ["Kings","Hockey","Ducks","Oilers", "ETC"],
        "MLS" : ["Galaxy","ETC"],
        "EPL" : ["Etc"],
        "Holiday" : ["Fireworks", "Christmas"],
        "NCAA" : ["Duke", "Wisconsin", "Florida"],
    ]
    
    static let data = [
        "NFL" : ["Chargers","Broncos","Rams","Patriots", "ETC"],
        "NBA" : ["Bulls","Wizards","Raptors","Lakers", "ETC"],
        "MLB" : ["Padres","Angels","Dodgers","Yankees", "ETC"],
        "NHL" : ["Kings","Hockey","Ducks","Oilers", "ETC"],
        "MLS" : ["Galaxy","ETC"],
        "EPL" : ["Etc"],
    ]
    
    static let initialData: [[String]] = [
        ["", "MLB", "Chicago White Sox", "", "", "000000", "C0C0C0", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", ""],
        ["", "MLB", "Baltimore Orioles", "", "", "ed4c09", "000000", "", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", ""],
        ["", "MLB", "Los Angeles Dodgers", "", "", "083C6B", "", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "MLB", "New York Yankees", "", "", "1C2841", "808080", "", "", "", "", "", "", "", "", "USA", "New York", "New York", ""],
        ["", "MLB", "Arizona Diamondbacks", "", "", "A71930", "000000", "DBCEAC", "", "", "", "", "", "", "", "USA", "", "Arizona", ""],
        ["", "MLB", "Texas Rangers", "", "", "BD1021", "003279", "", "", "", "", "", "", "", "", "USA", "", "Texas", ""],
        ["", "MLB", "San Diego Padres", "", "", "002147", "B4A76C", "", "", "", "", "", "", "", "", "USA", "San Diego", "California", ""],
        ["", "MLB", "Tampa Bay Rays", "", "", "00285D", "9ECEEE", "ffd700", "", "", "", "", "", "", "", "USA", "Tampa", "Florida", ""],
        ["", "MLB", "Toronto Blue Jays", "", "", "003DA5", "041E42", "DA291C", "", "", "", "", "", "", "", "Canada", "Toronta", "Ontario", ""],
        ["", "MLB", "Los Angeles Angels of Anaheim", "", "", "B71234", "002244", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "MLB", "Chicago Cubs", "", "", "003279", "CC0033", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", ""],
        ["", "MLB", "Colorado Rockies", "", "", "000000", "333366", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Colorado", ""],
        ["", "MLB", "Houston Astros", "", "", "072854", "FF7F00", "", "", "", "", "", "", "", "", "USA", "Houston", "Texas", ""],
        ["", "MLB", "Boston Red Sox", "", "", "C60C30", "002244", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", ""],
        ["", "MLB", "Milwaukee Brewers", "", "", "182B49", "92754C", "", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", ""],
        ["", "MLB", "Cleveland Indians", "", "", "003366", "d30335", "", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", ""],
        ["", "MLB", "Kansas City Royals", "", "", "15317E", "74B4FA", "", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", ""],
        ["", "MLB", "St Louis Cardinals", "", "", "c41e3a", "0A2252", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", ""],
        ["", "MLB", "Seattle Mariners", "", "", "0C2C56", "005C5C", "C0C0C0", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", ""],
        ["", "MLB", "Philadelphia Phillies", "", "", "BA0C2F", "003087", "", "", "", "", "", "", "", "", "USA", "Philadephia", "Pennsylvania", ""],
        ["", "MLB", "New York Mets", "", "", "002C77", "FB4F14", "", "", "", "", "", "", "", "", "USA", "New York", "New York", ""],
        ["", "MLB", "Atlanta Braves", "", "", "002F5F", "B71234", "", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", ""],
        ["", "MLB", "Oakland Athletics", "", "", "003831", "FFD800", "", "", "", "", "", "", "", "", "USA", "Oakland", "California", ""],
        ["", "MLB", "San Francisco Giants", "", "", "000000", "F2552C", "FFFDD0", "", "", "", "", "", "", "", "USA", "San Francisco", "California", ""],
        ["", "MLB", "Washington Nationals", "", "", "BA122B", "11225B", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", ""],
        ["", "MLB", "Miami Marlins", "", "", "000000", "F9423A", "8A8D8F", "0077C8", "FFD100", "", "", "", "", "", "USA", "Miami", "Florida", ""],
        ["", "MLB", "Detroit Tigers", "", "", "001742", "DE4406", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", ""],
        ["", "MLB", "Pittsburgh Pirates", "", "", "000000", "fdb829", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", ""],
        ["", "MLB", "Minnesota Twins", "", "", "072754", "C6011F", "", "", "", "", "", "", "", "", "USA", "", "Minnesota", ""],
        ["", "MLB", "Cincinnati Reds", "", "", "C6011F", "000000", "", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", ""],
        ["", "NHL", "San Jose Sharks", "", "", "05535D", "F38F20", "000000", "", "", "", "", "", "", "", "USA", "San Jose", "California", ""],
        ["", "NHL", "Detroit Red Wings", "", "", "EC1F26", "", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", ""],
        ["", "NHL", "Nashville Predators", "", "", "FDBB2F", "002E62", "", "", "", "", "", "", "", "", "USA", "Nashville", "Tennessee", ""],
        ["", "NHL", "Carolina Hurricanes", "", "", "E03A3E", "000000", "8E8E90", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", ""],
        ["", "NHL", "Boston Bruins", "", "", "000000", "FFC422", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", ""],
        ["", "NHL", "Columbus Blue Jackets", "", "", "00285C", "E03A3E", "A9B0B8", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", ""],
        ["", "NHL", "Florida Panthers", "", "", "C8213F", "002E5F", "D59C05", "", "", "", "", "", "", "", "USA", "", "Florida", ""],
        ["", "NHL", "Anaheim Ducks", "", "", "000000", "91764B", "EF5225", "", "", "", "", "", "", "", "USA", "Anaheim", "California", ""],
        ["", "NHL", "Buffalo Sabres", "", "", "002E62", "FDBB2F", "AEB6B9", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", ""],
        ["", "NHL", "Montreal Canadiens", "", "", "BF2F38", "213770", "", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", ""],
        ["", "NHL", "Edmonton Oilers", "", "", "003777", "E66A20", "", "", "", "", "", "", "", "", "Canada", "Edmonton", "Alberta", ""],
        ["", "NHL", "Pittsburgh Penguins", "", "", "000000", "D1BD80", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", ""],
        ["", "NHL", "New York Rangers", "", "", "0161AB", "E6393F", "", "", "", "", "", "", "", "", "USA", "New York", "New York", ""],
        ["", "NHL", "Washington Capitals", "", "", "CF132B", "00214E", "000000", "", "", "", "", "", "", "", "USA", "Washington", "DC", ""],
        ["", "NHL", "St Louis Blues", "", "", "0546A0", "FFC325", "101F48", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", ""],
        ["", "NHL", "Toronto Maple Leafs", "", "", "003777", "", "", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", ""],
        ["", "NHL", "Minnesota Wild", "", "", "025736", "BF2B37", "EFB410", "EEE3C7", "", "", "", "", "", "", "USA", "", "Minnesota", ""],
        ["", "NHL", "Dallas Stars", "", "", "006A4E", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", ""],
        ["", "NHL", "Winnipeg Jets", "", "", "002E62", "0168AB", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Winnipeg", "Manitoba", ""],
        ["", "NHL", "New Jersey Devils", "", "", "E03A3E", "000000", "", "", "", "", "", "", "", "", "USA", "", "New Jersey", ""],
        ["", "NHL", "Tampa Bay Lightning", "", "", "013E7D", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", ""],
        ["", "NHL", "Los Angeles Kings", "", "", "000000", "AFB7BA", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "NHL", "Calgary Flames", "", "", "E03A3E", "FFC758", "000000", "", "", "", "", "", "", "", "Canada", "Calgary", "Alberta", ""],
        ["", "NHL", "Chicago Blackhawks", "", "", "E3263A", "000000", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", ""],
        ["", "NHL", "Colorado Avalanche", "", "", "8B2942", "01548A", "000000", "A9B0B8", "", "", "", "", "", "", "USA", "", "Colorado", ""],
        ["", "NHL", "Arizona Coyotes", "", "", "841F27", "000000", "EFE1C6", "", "", "", "", "", "", "", "USA", "", "Arizona", ""],
        ["", "NHL", "Ottawa Senators", "", "", "E4173E", "000000", "D69F0F", "", "", "", "", "", "", "", "Canada", "Ottawa", "Ontario", ""],
        ["", "NHL", "New York Islanders", "", "", "00529B", "F57D31", "", "", "", "", "", "", "", "", "USA", "", "New York", ""],
        ["", "NHL", "Vancouver Canucks", "", "", "07346F", "047A4A", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", ""],
        ["", "NHL", "Philadelphia Flyers", "", "", "F47940", "000000", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", ""],
        ["", "NFL", "New Orleans Saints", "", "", "D2B887", "000000", "", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", ""],
        ["", "NFL", "Chicago Bears", "", "", "03202F", "DD4814", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", ""],
        ["", "NFL", "Pittsburgh Steelers", "", "", "000000", "F2C800", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", ""],
        ["", "NFL", "New England Patriots", "", "", "0D254C", "D6D6D6", "C80815", "", "", "", "", "", "", "", "USA", "New England", "", ""],
        ["", "NFL", "New York Jets", "", "", "0C371D", "", "", "", "", "", "", "", "", "", "USA", "", "New York", ""],
        ["", "NFL", "Carolina Panthers", "", "", "000000", "0088CE", "A5ACAF", "", "", "", "", "", "", "", "USA", "Carolina", "", ""],
        ["", "NFL", "San Francisco 49ers", "", "", "AF1E2C", "E6BE8A", "000000", "", "", "", "", "", "", "", "USA", "San Francisco", "California", ""],
        ["", "NFL", "Tampa Bay Buccaneers", "", "", "D60A0B", "89765F", "000000", "FF7A00", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", ""],
        ["", "NFL", "Philadelphia Eagles", "", "", "003B48", "000000", "708090", "C0C0C0", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", ""],
        ["", "NFL", "Indianapolis Colts", "", "", "003B7B", "", "", "", "", "", "", "", "", "", "USA", "Indianapolis", "Indiana", ""],
        ["", "NFL", "Seattle Seahawks", "", "", "06192E", "4EAE47", "ACB6BC", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", ""],
        ["", "NFL", "Arizona Cardinals", "test", "", "870619", "000000", "", "", "", "", "", "", "", "", "USA", "", "Arizona", ""],
        ["", "NFL", "Arizona Cardinals", "Alternate", "0.99", "111C24", "97233F", "", "", "", "", "", "", "", "", "USA", "", "Arizona", ""],
        ["", "NFL", "Atlanta Falcons", "", "", "BD0D18", "000000", "DCE0E5", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", ""],
        ["", "NFL", "Houston Texans", "", "", "02253A", "B31B34", "", "", "", "", "", "", "", "", "USA", "Houston", "Texas", ""],
        ["", "NFL", "Tennessee Titans", "", "", "648FCC", "000080", "FF0000", "C0C0C0", "", "", "", "", "", "", "USA", "", "Tennessee", ""],
        ["", "NFL", "Cleveland Browns", "", "", "26201E", "E34912", "", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", ""],
        ["", "NFL", "Cincinnati Bengals", "", "", "000000", "FB4F14", "", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", ""],
        ["", "NFL", "Oakland Raiders", "", "", "C4C8CB", "000000", "", "", "", "", "", "", "", "", "USA", "Oakland", "California", ""],
        ["", "NFL", "Buffalo Bills", "", "", "00338D", "C60C30", "", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", ""],
        ["", "NFL", "San Diego Chargers", "", "", "08214A", "EEC607", "5B92E5", "", "", "", "", "", "", "", "USA", "San Diego", "California", ""],
        ["", "NFL", "Miami Dolphins", "", "", "008d97", "015679", "F5811F", "", "", "", "", "", "", "", "USA", "Miami", "Florida", ""],
        ["", "NFL", "New York Giants", "", "", "192F6B", "CA001A", "808080", "", "", "", "", "", "", "", "USA", "", "New York", ""],
        ["", "NFL", "St Louis Rams", "", "", "13264B", "C9AF74", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", ""],
        ["", "NFL", "Jacksonville Jaguars", "", "", "000000", "D0B239", "007198", "", "", "", "", "", "", "", "USA", "Jacksonville", "Mississippi", ""],
        ["", "NFL", "Baltimore Ravens", "", "", "280353", "000000", "D0B240", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", ""],
        ["", "NFL", "Detroit Lions", "", "", "006DB0", "C5C7CF", "000000", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", ""],
        ["", "NFL", "Kansas City Chiefs", "", "", "B20032", "F2C800", "", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", ""],
        ["", "NFL", "Denver Broncos", "", "", "FB4F14", "002244", "", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", ""],
        ["", "NFL", "Washington Redskins", "", "", "773141", "FFB612", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", ""],
        ["", "NFL", "Green Bay Packers", "", "", "213D30", "FFCC00", "", "", "", "", "", "", "", "", "USA", "Green Bay", "Wisconsin", ""],
        ["", "NFL", "Minnesota Vikings", "", "", "4F2682", "FFC52F", "", "", "", "", "", "", "", "", "USA", "", "Minnesota", ""],
        ["", "NFL", "Dallas Cowboys", "", "", "002244", "8C8B8A", "", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", ""],
        ["", "MLS", "Chicago Fire", "", "", "AF2626", "0A174A", "8A8D8F", "", "", "", "", "", "", "", "USA", "Chiago", "Illinois", ""],
        ["", "MLS", "New England Revolution", "", "", "0A2141", "D80016", "8A8D8F", "", "", "", "", "", "", "", "USA", "New England", "", ""],
        ["", "MLS", "Toronto FC", "", "", "D80016", "313F49", "A1AAAD", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", ""],
        ["", "MLS", "FC Dallas", "", "", "CF0032", "07175C", "8A8D8F", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", ""],
        ["", "MLS", "Portland Timbers", "", "", "004812", "EBE72B", "", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", ""],
        ["", "MLS", "New York City FC", "", "", "6CADDF", "00285E", "FD4F00", "", "", "", "", "", "", "", "USA", "New York", "", ""],
        ["", "MLS", "New York Red Bulls", "", "", "D50031", "012055", "FFC800", "8A8D8F", "", "", "", "", "", "", "USA", "New York", "", ""],
        ["", "MLS", "Montreal Impact", "", "", "122089", "000000", "7A878F", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", ""],
        ["", "MLS", "DC United", "", "", "000000", "DD0000", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", ""],
        ["", "MLS", "Columbus Crew", "", "", "000000", "FFDB00", "8A8D8F", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", ""],
        ["", "MLS", "San Jose Earthquakes", "", "", "0051BA", "000000", "B1B4B2", "", "", "", "", "", "", "", "USA", "San Jose", "California", ""],
        ["", "MLS", "Philadelphia Union", "", "", "001B2D", "B18500", "348AE1", "", "", "", "", "", "", "", "USA", "", "Philadelphia", ""],
        ["", "MLS", "Colorado Rapids", "", "", "91022D", "85B7EA", "8A8D8F", "313F49", "", "", "", "", "", "", "USA", "Denver", "Colorado", ""],
        ["", "MLS", "Sporting Kansas City", "", "", "A4BBD7", "0A2141", "787775", "", "", "", "", "", "", "", "USA", "Kansas City", "Kansas", ""],
        ["", "MLS", "Seattle Sounders FC", "", "", "4F8A10", "11568C", "212930", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", ""],
        ["", "MLS", "Chivas USA", "", "", "AA002C", "031A43", "FFC800", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "MLS", "Orlando City SC", "", "", "633492", "FDE192", "", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", ""],
        ["", "MLS", "Real Salt Lake", "", "", "A50531", "013474", "F2D11A", "", "", "", "", "", "", "", "USA", "Salt Lake", "Utah", ""],
        ["", "MLS", "Vancouver Whitecaps FC", "", "", "12264C", "85B7EA", "838383", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", ""],
        ["", "MLS", "Houston Dynamo", "", "", "F36600", "2E2926", "85B7EA", "", "", "", "", "", "", "", "USA", "Houston", "Texas", ""],
        ["", "MLS", "Los Angeles Galaxy", "", "", "00245D", "004689", "F1AA00", "FFD200", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "EPL", "Southampton", "", "", "ED1A3B", "211E1F", "FFC20E", "", "", "", "", "", "", "", "UK", "Southampton", "England", ""],
        ["", "EPL", "Manchester United", "", "", "DA020E", "FFE500", "000000", "", "", "", "", "", "", "", "UK", "Manchester", "England", ""],
        ["", "EPL", "Liverpool", "", "", "00A398", "D00027", "FEF667", "", "", "", "", "", "", "", "UK", "Manchester", "England", ""],
        ["", "EPL", "Stoke City", "", "", "E03A3E", "1B449C", "", "", "", "", "", "", "", "", "UK", "Stoke", "England", ""],
        ["", "EPL", "Tottenham Hotspur", "", "", "001C58", "", "", "", "", "", "", "", "", "", "UK", "Tottenham", "England", ""],
        ["", "EPL", "Burnley", "", "", "8CCCE5", "53162F", "F9EC34", "", "", "", "", "", "", "", "UK", "Burnley", "England", ""],
        ["", "EPL", "West Ham United", "", "", "60223B", "F7C240", "5299C6", "", "", "", "", "", "", "", "UK", "West Ham", "England", ""],
        ["", "EPL", "Aston Villa", "", "", "94BEE5", "7A003C", "FFE600", "", "", "", "", "", "", "", "UK", "Witton", "England", ""],
        ["", "EPL", "Swansea City", "", "", "000000", "", "", "", "", "", "", "", "", "", "UK", "Swansea", "Wales", ""],
        ["", "EPL", "Arsenal", "", "", "EF0107", "023474", "9C824A", "", "", "", "", "", "", "", "UK", "Holloway", "England", ""],
        ["", "EPL", "Crystal Palace", "", "", "1B458F", "C4122E", "A7A5A6", "", "", "", "", "", "", "", "UK", "South Norwood", "England", ""],
        ["", "EPL", "West Bromwich Albion", "", "", "091453", "", "", "", "", "", "", "", "", "", "UK", "West Bromwich", "England", ""],
        ["", "EPL", "Queens Park Rangers", "", "", "005CAB", "", "", "", "", "", "", "", "", "", "UK", "Queens Park", "England", ""],
        ["", "EPL", "Newcastle United", "", "", "00B6F1", "BBBDBF", "231F20", "F0B83D", "", "", "", "", "", "", "UK", "Newcastle", "England", ""],
        ["", "EPL", "Everton", "", "", "274488", "", "", "", "", "", "", "", "", "", "UK", "Liverpool", "England", ""],
        ["", "EPL", "Hull City", "", "", "F5A12D", "000000", "", "", "", "", "", "", "", "", "UK", "Yorkshire", "England", ""],
        ["", "EPL", "Chelsea", "", "", "034694", "DBA111", "ED1C24", "", "", "", "", "", "", "", "UK", "Chelsea", "England", ""],
        ["", "EPL", "Leicester City", "", "", "FDBE11", "0053A0", "", "", "", "", "", "", "", "", "UK", "Leicester", "England", ""],
        ["", "EPL", "Sunderland", "", "", "EB172B", "A68A26", "211E1E", "", "", "", "", "", "", "", "UK", "Sunderland", "England", ""],
        ["", "EPL", "Manchester City", "", "", "5CBFEB", "FFCE65", "", "", "", "", "", "", "", "", "UK", "Manchester", "England", ""],
        ["", "NBA", "New York Knicks", "", "", "0953A0", "FF7518", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "New York", ""],
        ["", "NBA", "Los Angeles Lakers", "", "", "4A2583", "F5AF1B", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "NBA", "Memphis Grizzlies", "", "", "001F70", "7399C6", "BED4E9", "FDB927", "", "", "", "", "", "", "USA", "Memphis", "Tennessee", ""],
        ["", "NBA", "San Antonio Spurs", "", "", "000000", "BEC8C9", "", "", "", "", "", "", "", "", "USA", "San Antonio", "Texas", ""],
        ["", "NBA", "New Orleans Pelicans", "", "", "002B5C", "B4975A", "E31836", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", ""],
        ["", "NBA", "Houston Rockets", "", "", "CE1138", "CCCCCC", "000000", "", "", "", "", "", "", "", "USA", "Houston", "Texas", ""],
        ["", "NBA", "Detroit Pistons", "", "", "00519A", "EB003C", "041e40", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", ""],
        ["", "NBA", "Boston Celtics", "", "", "009E60", "000000", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", ""],
        ["", "NBA", "Miami Heat", "", "", "000000", "B62630", "FF9F00", "", "", "", "", "", "", "", "USA", "Miami", "Florida", ""],
        ["", "NBA", "Orlando Magic", "", "", "0047AB", "000000", "708090", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", ""],
        ["", "NBA", "Portland Trail Blazers", "", "", "F0163A", "B6BFBF", "000000", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", ""],
        ["", "NBA", "Golden State Warriors", "", "", "04529C", "FFCC33", "", "", "", "", "", "", "", "", "USA", "Golden State", "California", ""],
        ["", "NBA", "Chicago Bulls", "", "", "D4001F", "000000", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", ""],
        ["", "NBA", "Washington Wizards", "", "", "002B5C", "E31837", "C4CDD4", "", "", "", "", "", "", "", "USA", "Washington", "DC", ""],
        ["", "NBA", "Dallas Mavericks", "", "", "0b60AD", "072156", "A9A9A9", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", ""],
        ["", "NBA", "Minnesota Timberwolves", "", "", "0F4D92", "000000", "8C92AC", "50C878", "", "", "", "", "", "", "USA", "", "Minnesota", ""],
        ["", "NBA", "Los Angeles Clippers", "", "", "EE2944", "146AA2", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", ""],
        ["", "NBA", "Oklahoma City Thunder", "", "", "007DC3", "F05133", "FDBB30", "002D62", "", "", "", "", "", "", "USA", "Oklahoma City", "Oklahoma", ""],
        ["", "NBA", "Charlotte Hornets", "", "", "1D1160", "008CA8", "A1A1A4", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", ""],
        ["", "NBA", "Milwaukee Bucks", "", "", "003614", "E32636", "C0C0C0", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", ""],
        ["", "NBA", "Toronto Raptors", "", "", "B31B1B", "000000", "708090", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", ""],
        ["", "NBA", "Utah Jazz", "", "", "00275D", "FF9100", "0D4006", "B5B5B5", "", "", "", "", "", "", "USA", "", "Utah", ""],
        ["", "NBA", "Phoenix Suns", "", "", "1C105E", "E65F20", "000000", "B1B3B3", "", "", "", "", "", "", "USA", "Phoenix", "Arizona", ""],
        ["", "NBA", "Sacramento Kings", "", "", "753BBD", "000000", "8A8D8F", "", "", "", "", "", "", "", "USA", "Sacramento", "California", ""],
        ["", "NBA", "Philadelphia 76ers", "", "", "0046AD", "D0103A", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", ""],
        ["", "NBA", "Cleveland Cavaliers", "", "", "860038", "FDBB30", "002D62", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", ""],
        ["", "NBA", "Atlanta Hawks", "", "", "000080", "FF0000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", ""],
        ["", "NBA", "Brooklyn Nets", "", "", "000000", "", "", "", "", "", "", "", "", "", "USA", "Brooklyn", "New York", ""],
        ["", "NBA", "Indiana Pacers", "", "", "092C57", "FFC322", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Indiana", ""],
        ["", "NBA", "Denver Nuggets", "", "", "4b90CD", "FDB827", "002D62", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", ""],
    ]
    
}