//
//  store-data.swift
//  whoscheering
//
//  Created by Conrad on 5/25/15.
//  Copyright (c) 2015 Conrad. All rights reserved.
//

import Foundation


struct StoreData{
    //static let categories = ["NFL","NBA","MLB","NHL","MLS","EPL"]
    static let categories = details.keys.array
    
    //add IAP id for each team
    //add COLORS for each team
    //details.category.team.colors
    //details.category.team.name
    //details.category.team.appid
    //possibly simplify categories to be a function return, gather from the details array
    
    static let details = [
        "NFL" : ["Chargers","Broncos","Rams","Patriots", "ETC"],
        "NBA" : ["Bulls","Wizards","Raptors","Lakers", "ETC"],
        "MLB" : ["Padres","Angels","Dodgers","Yankees", "ETC"],
        "NHL" : ["Kings","Hockey","Ducks","Oilers", "ETC"],
        "MLS" : ["Galaxy","ETC"],
        "EPL" : ["Etc"],
        "Holiday" : ["Fireworks", "Christmas"],
        "NCAA" : ["Duke", "Wisconsin", "Florida"],
    ]
    
    static let data = [
        "NFL" : ["Chargers","Broncos","Rams","Patriots", "ETC"],
        "NBA" : ["Bulls","Wizards","Raptors","Lakers", "ETC"],
        "MLB" : ["Padres","Angels","Dodgers","Yankees", "ETC"],
        "NHL" : ["Kings","Hockey","Ducks","Oilers", "ETC"],
        "MLS" : ["Galaxy","ETC"],
        "EPL" : ["Etc"],
    ]
    
    static let initialData: [[String]] = [
        ["com.flashforceapp.whitesoxaway", "MLB", "Chicago White Sox", "Away", "0.99", "CCCCCC", "FFFFFF", "000000", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4_2", ""],
        ["com.flashforceapp.whitesoxbluered", "MLB", "Chicago White Sox", "Blue/Red Alternate", "0.99", "003366", "CC3333", "FFFFFF", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4_2", ""],
        ["com.flashforceapp.whitesoxdefault", "MLB", "Chicago White Sox", "", "0.99", "000000", "C0C0C0", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", ""],
        ["com.flashforceapp.oriolesaway", "MLB", "Baltimore Orioles", "Away Gray", "0.99", "A4AAAC", "ed4c09", "000000", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", ""],
        ["com.flashforceapp.oriolesorange", "MLB", "Baltimore Orioles", "Orange Alternate", "0.99", "ed4c09", "000000", "FFFFFF", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", ""],
        ["com.flashforceapp.oriolesblack", "MLB", "Baltimore Orioles", "Black Alternate", "0.99", "FFFFFF", "ed4c09", "", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4", ""],
        ["com.flashforceapp.oriolesdefault", "MLB", "Baltimore Orioles", "", "0.99", "FFFFFF", "ed4c09", "000000", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", ""],
        ["com.flashforceapp.dodgersdefault", "MLB", "Los Angeles Dodgers", "", "0.99", "083C6B", "", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6", ""],
        ["com.flashforceapp.yankeesdefault", "MLB", "New York Yankees", "", "0.99", "1C2841", "808080", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", ""],
        ["com.flashforceapp.diamondbacksdefault", "MLB", "Arizona Diamondbacks", "", "0.99", "A71930", "000000", "DBCEAC", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4_2", ""],
        ["com.flashforceapp.rangersdefault", "MLB", "Texas Rangers", "", "0.99", "BD1021", "003279", "", "", "", "", "", "", "", "", "USA", "", "Texas", "6_4", ""],
        ["com.flashforceapp.padresdefault", "MLB", "San Diego Padres", "", "0.99", "002147", "B4A76C", "", "", "", "", "", "", "", "", "USA", "San Diego", "California", "6_4", ""],
        ["com.flashforceapp.raysdefault", "MLB", "Tampa Bay Rays", "", "0.99", "00285D", "9ECEEE", "ffd700", "", "", "", "", "", "", "", "USA", "Tampa", "Florida", "6_4_2", ""],
        ["com.flashforceapp.bluejaysdefault", "MLB", "Toronto Blue Jays", "", "0.99", "003DA5", "041E42", "DA291C", "", "", "", "", "", "", "", "Canada", "Toronta", "Ontario", "6_4_2", ""],
        ["com.flashforceapp.angelsdefault", "MLB", "Los Angeles Angels of Anaheim", "", "0.99", "B71234", "002244", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", ""],
        ["com.flashforceapp.cubsdefault", "MLB", "Chicago Cubs", "", "0.99", "003279", "CC0033", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", ""],
        ["com.flashforceapp.rockiesdefault", "MLB", "Colorado Rockies", "", "0.99", "000000", "333366", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Colorado", "6_4_2", ""],
        ["com.flashforceapp.astrosdefault", "MLB", "Houston Astros", "", "0.99", "072854", "FF7F00", "", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4", ""],
        ["com.flashforceapp.redsoxdefault", "MLB", "Boston Red Sox", "", "0.99", "C60C30", "002244", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", ""],
        ["com.flashforceapp.brewersdefault", "MLB", "Milwaukee Brewers", "", "0.99", "182B49", "92754C", "", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", "6_4", ""],
        ["com.flashforceapp.indiansdefault", "MLB", "Cleveland Indians", "", "0.99", "003366", "d30335", "", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4", ""],
        ["com.flashforceapp.royalsdefault", "MLB", "Kansas City Royals", "", "0.99", "15317E", "74B4FA", "", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", "6_4", ""],
        ["com.flashforceapp.stcardinalsdefault", "MLB", "St Louis Cardinals", "", "0.99", "c41e3a", "0A2252", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4", ""],
        ["com.flashforceapp.marinersdefault", "MLB", "Seattle Mariners", "", "0.99", "0C2C56", "005C5C", "C0C0C0", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", ""],
        ["com.flashforceapp.philliesdefault", "MLB", "Philadelphia Phillies", "", "0.99", "BA0C2F", "003087", "", "", "", "", "", "", "", "", "USA", "Philadephia", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.metsdefault", "MLB", "New York Mets", "", "0.99", "002C77", "FB4F14", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", ""],
        ["com.flashforceapp.bravesdefault", "MLB", "Atlanta Braves", "", "0.99", "002F5F", "B71234", "", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4", ""],
        ["com.flashforceapp.athleticsdefault", "MLB", "Oakland Athletics", "", "0.99", "003831", "FFD800", "", "", "", "", "", "", "", "", "USA", "Oakland", "California", "6_4", ""],
        ["com.flashforceapp.sfgiantsdefault", "MLB", "San Francisco Giants", "", "0.99", "000000", "F2552C", "FFFDD0", "", "", "", "", "", "", "", "USA", "San Francisco", "California", "6_4_2", ""],
        ["com.flashforceapp.nationalsdefault", "MLB", "Washington Nationals", "", "0.99", "BA122B", "11225B", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", ""],
        ["com.flashforceapp.marlinsdefault", "MLB", "Miami Marlins", "", "0.99", "000000", "F9423A", "8A8D8F", "0077C8", "FFD100", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2_2_2", ""],
        ["com.flashforceapp.tigersdefault", "MLB", "Detroit Tigers", "", "0.99", "001742", "DE4406", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4", ""],
        ["com.flashforceapp.piratesdefault", "MLB", "Pittsburgh Pirates", "", "0.99", "000000", "fdb829", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.twinsdefault", "MLB", "Minnesota Twins", "", "0.99", "072754", "C6011F", "", "", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4", ""],
        ["com.flashforceapp.redsdefault", "MLB", "Cincinnati Reds", "", "0.99", "C6011F", "000000", "", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", "6_4", ""],
        ["com.flashforceapp.sharksdefault", "NHL", "San Jose Sharks", "", "0.99", "05535D", "F38F20", "000000", "", "", "", "", "", "", "", "USA", "San Jose", "California", "6_4_2", ""],
        ["com.flashforceapp.redwingsdefault", "NHL", "Detroit Red Wings", "", "0.99", "EC1F26", "", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6", ""],
        ["com.flashforceapp.predatorsdefault", "NHL", "Nashville Predators", "", "0.99", "FDBB2F", "002E62", "", "", "", "", "", "", "", "", "USA", "Nashville", "Tennessee", "6_4", ""],
        ["com.flashforceapp.hurricanesdefault", "NHL", "Carolina Hurricanes", "", "0.99", "E03A3E", "000000", "8E8E90", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", "6_4_2", ""],
        ["com.flashforceapp.bruinsdefault", "NHL", "Boston Bruins", "", "0.99", "000000", "FFC422", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", ""],
        ["com.flashforceapp.bluejacketsdefault", "NHL", "Columbus Blue Jackets", "", "0.99", "00285C", "E03A3E", "A9B0B8", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", "6_4_2", ""],
        ["com.flashforceapp.flpanthersdefault", "NHL", "Florida Panthers", "", "0.99", "C8213F", "002E5F", "D59C05", "", "", "", "", "", "", "", "USA", "", "Florida", "6_4_2", ""],
        ["com.flashforceapp.ducksdefault", "NHL", "Anaheim Ducks", "", "0.99", "000000", "91764B", "EF5225", "", "", "", "", "", "", "", "USA", "Anaheim", "California", "6_4_2", ""],
        ["com.flashforceapp.sabresdefault", "NHL", "Buffalo Sabres", "", "0.99", "002E62", "FDBB2F", "AEB6B9", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", "6_4_2", ""],
        ["com.flashforceapp.canadiensdefault", "NHL", "Montreal Canadiens", "", "0.99", "BF2F38", "213770", "", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", "6_4", ""],
        ["com.flashforceapp.oilsdefault", "NHL", "Edmonton Oilers", "", "0.99", "003777", "E66A20", "", "", "", "", "", "", "", "", "Canada", "Edmonton", "Alberta", "6_4", ""],
        ["com.flashforceapp.pengiunsdefault", "NHL", "Pittsburgh Penguins", "", "0.99", "000000", "D1BD80", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.nyrangersdefault", "NHL", "New York Rangers", "", "0.99", "0161AB", "E6393F", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", ""],
        ["com.flashforceapp.capitalsdefault", "NHL", "Washington Capitals", "", "0.99", "CF132B", "00214E", "000000", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4_2", ""],
        ["com.flashforceapp.bluesdefault", "NHL", "St Louis Blues", "", "0.99", "0546A0", "FFC325", "101F48", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4_2", ""],
        ["com.flashforceapp.mapleleafsdefault", "NHL", "Toronto Maple Leafs", "", "0.99", "003777", "", "", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6", ""],
        ["com.flashforceapp.wilddefault", "NHL", "Minnesota Wild", "", "0.99", "025736", "BF2B37", "EFB410", "EEE3C7", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4_2_2", ""],
        ["com.flashforceapp.starsdefault", "NHL", "Dallas Stars", "", "0.99", "006A4E", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", ""],
        ["com.flashforceapp.wjetsdefault", "NHL", "Winnipeg Jets", "", "0.99", "002E62", "0168AB", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Winnipeg", "Manitoba", "6_4_2", ""],
        ["com.flashforceapp.devilsdefault", "NHL", "New Jersey Devils", "", "0.99", "E03A3E", "000000", "", "", "", "", "", "", "", "", "USA", "", "New Jersey", "6_4", ""],
        ["com.flashforceapp.lightningdefault", "NHL", "Tampa Bay Lightning", "", "0.99", "013E7D", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", "6_4_2", ""],
        ["com.flashforceapp.kingsdefault", "NHL", "Los Angeles Kings", "", "0.99", "000000", "AFB7BA", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", ""],
        ["com.flashforceapp.flamesdefault", "NHL", "Calgary Flames", "", "0.99", "E03A3E", "FFC758", "000000", "", "", "", "", "", "", "", "Canada", "Calgary", "Alberta", "6_4_2", ""],
        ["com.flashforceapp.blackhawksdefault", "NHL", "Chicago Blackhawks", "", "0.99", "E3263A", "000000", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", ""],
        ["com.flashforceapp.avalancedefault", "NHL", "Colorado Avalanche", "", "0.99", "8B2942", "01548A", "000000", "A9B0B8", "", "", "", "", "", "", "USA", "", "Colorado", "6_4_2_2", ""],
        ["com.flashforceapp.coyotesdefault", "NHL", "Arizona Coyotes", "", "0.99", "841F27", "000000", "EFE1C6", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4_2", ""],
        ["com.flashforceapp.senatorsdefault", "NHL", "Ottawa Senators", "", "0.99", "E4173E", "000000", "D69F0F", "", "", "", "", "", "", "", "Canada", "Ottawa", "Ontario", "6_4_2", ""],
        ["com.flashforceapp.islandersdefault", "NHL", "New York Islanders", "", "0.99", "00529B", "F57D31", "", "", "", "", "", "", "", "", "USA", "", "New York", "6_4", ""],
        ["com.flashforceapp.canucksdefault", "NHL", "Vancouver Canucks", "", "0.99", "07346F", "047A4A", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", "6_4_2", ""],
        ["com.flashforceapp.flyersdefault", "NHL", "Philadelphia Flyers", "", "0.99", "F47940", "000000", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.saintsdefault", "NFL", "New Orleans Saints", "", "0.99", "D2B887", "000000", "", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", "6_4", ""],
        ["com.flashforceapp.bearsdefault", "NFL", "Chicago Bears", "", "0.99", "03202F", "DD4814", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", ""],
        ["com.flashforceapp.steelersdefault", "NFL", "Pittsburgh Steelers", "", "0.99", "000000", "F2C800", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.patriotsdefault", "NFL", "New England Patriots", "", "0.99", "0D254C", "D6D6D6", "C80815", "", "", "", "", "", "", "", "USA", "New England", "", "6_4_2", ""],
        ["com.flashforceapp.jetsdefault", "NFL", "New York Jets", "", "0.99", "0C371D", "", "", "", "", "", "", "", "", "", "USA", "", "New York", "6", ""],
        ["com.flashforceapp.panthersdefault", "NFL", "Carolina Panthers", "", "0.99", "000000", "0088CE", "A5ACAF", "", "", "", "", "", "", "", "USA", "Carolina", "", "6_4_2", ""],
        ["com.flashforceapp.fortyninersdefault", "NFL", "San Francisco 49ers", "", "0.99", "AF1E2C", "E6BE8A", "000000", "", "", "", "", "", "", "", "USA", "San Francisco", "California", "6_4_2", ""],
        ["com.flashforceapp.buccaneersdefault", "NFL", "Tampa Bay Buccaneers", "", "0.99", "D60A0B", "89765F", "000000", "FF7A00", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", "6_4_2_2", ""],
        ["com.flashforceapp.eaglesdefault", "NFL", "Philadelphia Eagles", "", "0.99", "003B48", "000000", "708090", "C0C0C0", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4_2_2", ""],
        ["com.flashforceapp.coltsdefault", "NFL", "Indianapolis Colts", "", "0.99", "003B7B", "", "", "", "", "", "", "", "", "", "USA", "Indianapolis", "Indiana", "6", ""],
        ["com.flashforceapp.seahawksdefault", "NFL", "Seattle Seahawks", "", "0.99", "06192E", "4EAE47", "ACB6BC", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", ""],
        ["com.flashforceapp.cardinalsalt", "NFL", "Arizona Cardinals", "Alternate", "0.99", "111C24", "97233F", "", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4", ""],
        ["com.flashforceapp.cardinalsdefault", "NFL", "Arizona Cardinals", "", "0.99", "870619", "000000", "", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4", ""],
        ["com.flashforceapp.falconsdefault", "NFL", "Atlanta Falcons", "", "0.99", "BD0D18", "000000", "DCE0E5", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4_2", ""],
        ["com.flashforceapp.texansdefault", "NFL", "Houston Texans", "", "0.99", "02253A", "B31B34", "", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4", ""],
        ["com.flashforceapp.titansdefault", "NFL", "Tennessee Titans", "", "0.99", "648FCC", "000080", "FF0000", "C0C0C0", "", "", "", "", "", "", "USA", "", "Tennessee", "6_4_2_2", ""],
        ["com.flashforceapp.brownsdefault", "NFL", "Cleveland Browns", "", "0.99", "26201E", "E34912", "", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4", ""],
        ["com.flashforceapp.bengalsdefault", "NFL", "Cincinnati Bengals", "", "0.99", "000000", "FB4F14", "", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", "6_4", ""],
        ["com.flashforceapp.raidersdefault", "NFL", "Oakland Raiders", "", "0.99", "C4C8CB", "000000", "", "", "", "", "", "", "", "", "USA", "Oakland", "California", "6_4", ""],
        ["com.flashforceapp.billsdefault", "NFL", "Buffalo Bills", "", "0.99", "00338D", "C60C30", "", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", "6_4", ""],
        ["com.flashforceapp.chargersdefault", "NFL", "San Diego Chargers", "", "0.99", "08214A", "EEC607", "5B92E5", "", "", "", "", "", "", "", "USA", "San Diego", "California", "6_4_2_2", ""],
        ["com.flashforceapp.dolphicsdefault", "NFL", "Miami Dolphins", "", "0.99", "008d97", "015679", "F5811F", "", "", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2", ""],
        ["com.flashforceapp.giantsdefault", "NFL", "New York Giants", "", "0.99", "192F6B", "CA001A", "808080", "", "", "", "", "", "", "", "USA", "", "New York", "6_4_2", ""],
        ["com.flashforceapp.ramsdefault", "NFL", "St Louis Rams", "", "0.99", "13264B", "C9AF74", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4", ""],
        ["com.flashforceapp.jaguarsdefault", "NFL", "Jacksonville Jaguars", "", "0.99", "000000", "D0B239", "007198", "", "", "", "", "", "", "", "USA", "Jacksonville", "Mississippi", "6_4_2", ""],
        ["com.flashforceapp.ravensdefault", "NFL", "Baltimore Ravens", "", "0.99", "280353", "000000", "D0B240", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", ""],
        ["com.flashforceapp.lionsdefault", "NFL", "Detroit Lions", "", "0.99", "006DB0", "C5C7CF", "000000", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4_2", ""],
        ["com.flashforceapp.chiefsdefault", "NFL", "Kansas City Chiefs", "", "0.99", "B20032", "F2C800", "", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", "6_4", ""],
        ["com.flashforceapp.broncosdefault", "NFL", "Denver Broncos", "", "0.99", "FB4F14", "002244", "", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4", ""],
        ["com.flashforceapp.redskinsdefault", "NFL", "Washington Redskins", "", "0.99", "773141", "FFB612", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", ""],
        ["com.flashforceapp.packersdefault", "NFL", "Green Bay Packers", "", "0.99", "213D30", "FFCC00", "", "", "", "", "", "", "", "", "USA", "Green Bay", "Wisconsin", "6_4", ""],
        ["com.flashforceapp.vikingsdefault", "NFL", "Minnesota Vikings", "", "0.99", "4F2682", "FFC52F", "", "", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4", ""],
        ["com.flashforceapp.cowboysdefault", "NFL", "Dallas Cowboys", "", "0.99", "002244", "8C8B8A", "", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4", ""],
        ["com.flashforceapp.firedefault", "MLS", "Chicago Fire", "", "0.99", "AF2626", "0A174A", "8A8D8F", "", "", "", "", "", "", "", "USA", "Chiago", "Illinois", "6_4_2", ""],
        ["com.flashforceapp.revolutiondefault", "MLS", "New England Revolution", "", "0.99", "0A2141", "D80016", "8A8D8F", "", "", "", "", "", "", "", "USA", "New England", "", "6_4_2", ""],
        ["com.flashforceapp.torontofcdefault", "MLS", "Toronto FC", "", "0.99", "D80016", "313F49", "A1AAAD", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6_4_2", ""],
        ["com.flashforceapp.fcdallasdefault", "MLS", "FC Dallas", "", "0.99", "CF0032", "07175C", "8A8D8F", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", ""],
        ["com.flashforceapp.timbersdefault", "MLS", "Portland Timbers", "", "0.99", "004812", "EBE72B", "", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", "6_4", ""],
        ["com.flashforceapp.nycfcdefault", "MLS", "New York City FC", "", "0.99", "6CADDF", "00285E", "FD4F00", "", "", "", "", "", "", "", "USA", "New York", "", "6_4_2", ""],
        ["com.flashforceapp.redbullsdefault", "MLS", "New York Red Bulls", "", "0.99", "D50031", "012055", "FFC800", "8A8D8F", "", "", "", "", "", "", "USA", "New York", "", "6_4_2_2", ""],
        ["com.flashforceapp.impactdefault", "MLS", "Montreal Impact", "", "0.99", "122089", "000000", "7A878F", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", "6_4_2", ""],
        ["com.flashforceapp.dcuniteddefault", "MLS", "DC United", "", "0.99", "000000", "DD0000", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", ""],
        ["com.flashforceapp.crewdefault", "MLS", "Columbus Crew", "", "0.99", "000000", "FFDB00", "8A8D8F", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", "6_4_2", ""],
        ["com.flashforceapp.earthquakesdefault", "MLS", "San Jose Earthquakes", "", "0.99", "0051BA", "000000", "B1B4B2", "", "", "", "", "", "", "", "USA", "San Jose", "California", "6_4_2", ""],
        ["com.flashforceapp.uniondefault", "MLS", "Philadelphia Union", "", "0.99", "001B2D", "B18500", "348AE1", "", "", "", "", "", "", "", "USA", "", "Philadelphia", "6_4_2", ""],
        ["com.flashforceapp.rapidsdefault", "MLS", "Colorado Rapids", "", "0.99", "91022D", "85B7EA", "8A8D8F", "313F49", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4_2_2", ""],
        ["com.flashforceapp.sportingkcdefault", "MLS", "Sporting Kansas City", "", "0.99", "A4BBD7", "0A2141", "787775", "", "", "", "", "", "", "", "USA", "Kansas City", "Kansas", "6_4_2", ""],
        ["com.flashforceapp.soundersfcdefault", "MLS", "Seattle Sounders FC", "", "0.99", "4F8A10", "11568C", "212930", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", ""],
        ["com.flashforceapp.chivasusadefault", "MLS", "Chivas USA", "", "0.99", "AA002C", "031A43", "FFC800", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4_2", ""],
        ["com.flashforceapp.orlandoscdefault", "MLS", "Orlando City SC", "", "0.99", "633492", "FDE192", "", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", "6_4", ""],
        ["com.flashforceapp.realsldefault", "MLS", "Real Salt Lake", "", "0.99", "A50531", "013474", "F2D11A", "", "", "", "", "", "", "", "USA", "Salt Lake", "Utah", "6_4_2", ""],
        ["com.flashforceapp.whitecapsfcdefault", "MLS", "Vancouver Whitecaps FC", "", "0.99", "12264C", "85B7EA", "838383", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", "6_4_2", ""],
        ["com.flashforceapp.dynamodefault", "MLS", "Houston Dynamo", "", "0.99", "F36600", "2E2926", "85B7EA", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4_2", ""],
        ["com.flashforceapp.lagalaxydefault", "MLS", "Los Angeles Galaxy", "", "0.99", "00245D", "004689", "F1AA00", "FFD200", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4_2_2", ""],
        ["com.flashforceapp.southamptondefault", "EPL", "Southampton", "", "0.99", "ED1A3B", "211E1F", "FFC20E", "", "", "", "", "", "", "", "UK", "Southampton", "England", "6_4_2", ""],
        ["com.flashforceapp.manchuniteddefault", "EPL", "Manchester United", "", "0.99", "DA020E", "FFE500", "000000", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4_2", ""],
        ["com.flashforceapp.liverpoolepldefault", "EPL", "Liverpool", "", "0.99", "00A398", "D00027", "FEF667", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4_2", ""],
        ["com.flashforceapp.stokecityepldefault", "EPL", "Stoke City", "", "0.99", "E03A3E", "1B449C", "", "", "", "", "", "", "", "", "UK", "Stoke", "England", "6_4", ""],
        ["com.flashforceapp.hotspurdefault", "EPL", "Tottenham Hotspur", "", "0.99", "001C58", "", "", "", "", "", "", "", "", "", "UK", "Tottenham", "England", "6", ""],
        ["com.flashforceapp.burnleydefault", "EPL", "Burnley", "", "0.99", "8CCCE5", "53162F", "F9EC34", "", "", "", "", "", "", "", "UK", "Burnley", "England", "6_4_2", ""],
        ["com.flashforceapp.westhamdefault", "EPL", "West Ham United", "", "0.99", "60223B", "F7C240", "5299C6", "", "", "", "", "", "", "", "UK", "West Ham", "England", "6_4_2", ""],
        ["com.flashforceapp.astonvilladefault", "EPL", "Aston Villa", "", "0.99", "94BEE5", "7A003C", "FFE600", "", "", "", "", "", "", "", "UK", "Witton", "England", "6_4_2", ""],
        ["com.flashforceapp.swanseadefault", "EPL", "Swansea City", "", "0.99", "000000", "", "", "", "", "", "", "", "", "", "UK", "Swansea", "Wales", "6", ""],
        ["com.flashforceapp.arsenaldefault", "EPL", "Arsenal", "", "0.99", "EF0107", "023474", "9C824A", "", "", "", "", "", "", "", "UK", "Holloway", "England", "6_4_2", ""],
        ["com.flashforceapp.crystalpalacedefault", "EPL", "Crystal Palace", "", "0.99", "1B458F", "C4122E", "A7A5A6", "", "", "", "", "", "", "", "UK", "South Norwood", "England", "6_4_2", ""],
        ["com.flashforceapp.bromwichalbiondefault", "EPL", "West Bromwich Albion", "", "0.99", "091453", "", "", "", "", "", "", "", "", "", "UK", "West Bromwich", "England", "6", ""],
        ["com.flashforceapp.parkrangersdefault", "EPL", "Queens Park Rangers", "", "0.99", "005CAB", "", "", "", "", "", "", "", "", "", "UK", "Queens Park", "England", "6", ""],
        ["com.flashforceapp.newcastleuniteddefault", "EPL", "Newcastle United", "", "0.99", "00B6F1", "BBBDBF", "231F20", "F0B83D", "", "", "", "", "", "", "UK", "Newcastle", "England", "6_4_2_2", ""],
        ["com.flashforceapp.evertonepldefault", "EPL", "Everton", "", "0.99", "274488", "", "", "", "", "", "", "", "", "", "UK", "Liverpool", "England", "6", ""],
        ["com.flashforceapp.hullcityepldefault", "EPL", "Hull City", "", "0.99", "F5A12D", "000000", "", "", "", "", "", "", "", "", "UK", "Yorkshire", "England", "6_4", ""],
        ["com.flashforceapp.chelseaepldefault", "EPL", "Chelsea", "", "0.99", "034694", "DBA111", "ED1C24", "", "", "", "", "", "", "", "UK", "Chelsea", "England", "6_4_2", ""],
        ["com.flashforceapp.leicesterepldefault", "EPL", "Leicester City", "", "0.99", "FDBE11", "0053A0", "", "", "", "", "", "", "", "", "UK", "Leicester", "England", "6_4", ""],
        ["com.flashforceapp.sunderlandepldefault", "EPL", "Sunderland", "", "0.99", "EB172B", "A68A26", "211E1E", "", "", "", "", "", "", "", "UK", "Sunderland", "England", "6_4_2", ""],
        ["com.flashforceapp.manchesterepldefault", "EPL", "Manchester City", "", "0.99", "5CBFEB", "FFCE65", "", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4", ""],
        ["com.flashforceapp.knicksdefault", "NBA", "New York Knicks", "", "0.99", "0953A0", "FF7518", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "New York", "6_4_2", ""],
        ["com.flashforceapp.lakersdefault", "NBA", "Los Angeles Lakers", "", "0.99", "4A2583", "F5AF1B", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", ""],
        ["com.flashforceapp.grizzliesdefault", "NBA", "Memphis Grizzlies", "", "0.99", "001F70", "7399C6", "BED4E9", "FDB927", "", "", "", "", "", "", "USA", "Memphis", "Tennessee", "6_4_2_2", ""],
        ["com.flashforceapp.spursdefault", "NBA", "San Antonio Spurs", "", "0.99", "000000", "BEC8C9", "", "", "", "", "", "", "", "", "USA", "San Antonio", "Texas", "6_4", ""],
        ["com.flashforceapp.pelicansdefault", "NBA", "New Orleans Pelicans", "", "0.99", "002B5C", "B4975A", "E31836", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", "6_4_2", ""],
        ["com.flashforceapp.rocketsdefault", "NBA", "Houston Rockets", "", "0.99", "CE1138", "CCCCCC", "000000", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4_2", ""],
        ["com.flashforceapp.pistonsdefault", "NBA", "Detroit Pistons", "", "0.99", "00519A", "EB003C", "041e40", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4_2", ""],
        ["com.flashforceapp.celticsdefault", "NBA", "Boston Celtics", "", "0.99", "009E60", "000000", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", ""],
        ["com.flashforceapp.heatdefault", "NBA", "Miami Heat", "", "0.99", "000000", "B62630", "FF9F00", "", "", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2", ""],
        ["com.flashforceapp.magicdefault", "NBA", "Orlando Magic", "", "0.99", "0047AB", "000000", "708090", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", "6_4_2", ""],
        ["com.flashforceapp.trailblazersdefault", "NBA", "Portland Trail Blazers", "", "0.99", "F0163A", "B6BFBF", "000000", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", "6_4_2", ""],
        ["com.flashforceapp.warriorsdefault", "NBA", "Golden State Warriors", "", "0.99", "04529C", "FFCC33", "", "", "", "", "", "", "", "", "USA", "Golden State", "California", "6_4", ""],
        ["com.flashforceapp.bullsdefault", "NBA", "Chicago Bulls", "", "0.99", "D4001F", "000000", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", ""],
        ["com.flashforceapp.wizardsdefault", "NBA", "Washington Wizards", "", "0.99", "002B5C", "E31837", "C4CDD4", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4_2", ""],
        ["com.flashforceapp.mavericksdefault", "NBA", "Dallas Mavericks", "", "0.99", "0b60AD", "072156", "A9A9A9", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", ""],
        ["com.flashforceapp.timerwolvesdefault", "NBA", "Minnesota Timberwolves", "", "0.99", "0F4D92", "000000", "8C92AC", "50C878", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4_2_2", ""],
        ["com.flashforceapp.clippersdefault", "NBA", "Los Angeles Clippers", "", "0.99", "EE2944", "146AA2", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", ""],
        ["com.flashforceapp.thunderdefault", "NBA", "Oklahoma City Thunder", "", "0.99", "007DC3", "F05133", "FDBB30", "002D62", "", "", "", "", "", "", "USA", "Oklahoma City", "Oklahoma", "6_4_2_2", ""],
        ["com.flashforceapp.hornetsdefault", "NBA", "Charlotte Hornets", "", "0.99", "1D1160", "008CA8", "A1A1A4", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", "6_4_2", ""],
        ["com.flashforceapp.bucksdefault", "NBA", "Milwaukee Bucks", "", "0.99", "003614", "E32636", "C0C0C0", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", "6_4_2", ""],
        ["com.flashforceapp.raptorsdefault", "NBA", "Toronto Raptors", "", "0.99", "B31B1B", "000000", "708090", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6_4_2", ""],
        ["com.flashforceapp.jazzdefault", "NBA", "Utah Jazz", "", "0.99", "00275D", "FF9100", "0D4006", "B5B5B5", "", "", "", "", "", "", "USA", "", "Utah", "6_4_2_2", ""],
        ["com.flashforceapp.sunsdefault", "NBA", "Phoenix Suns", "", "0.99", "1C105E", "E65F20", "000000", "B1B3B3", "", "", "", "", "", "", "USA", "Phoenix", "Arizona", "6_4_2_2", ""],
        ["com.flashforceapp.sackingsdefault", "NBA", "Sacramento Kings", "", "0.99", "753BBD", "000000", "8A8D8F", "", "", "", "", "", "", "", "USA", "Sacramento", "California", "6_4_2", ""],
        ["com.flashforceapp.sevsixersdefault", "NBA", "Philadelphia 76ers", "", "0.99", "0046AD", "D0103A", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4", ""],
        ["com.flashforceapp.cavaliersdefault", "NBA", "Cleveland Cavaliers", "", "0.99", "860038", "FDBB30", "002D62", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4_2", ""],
        ["com.flashforceapp.hawksdefault", "NBA", "Atlanta Hawks", "", "0.99", "000080", "FF0000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4_2", ""],
        ["com.flashforceapp.netsdefault", "NBA", "Brooklyn Nets", "", "0.99", "000000", "", "", "", "", "", "", "", "", "", "USA", "Brooklyn", "New York", "6", ""],
        ["com.flashforceapp.pacersdefault", "NBA", "Indiana Pacers", "", "0.99", "092C57", "FFC322", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Indiana", "6_4_2", ""],
        ["com.flashforceapp.nuggetsdefault", "NBA", "Denver Nuggets", "", "0.99", "4b90CD", "FDB827", "002D62", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4_2", ""],
    ]
    
}