//
//  store-data.swift
//  whoscheering
//
//  Created by Conrad on 5/25/15.
//  Copyright (c) 2015 Conrad. All rights reserved.
//

import Foundation


struct StoreData{
    
    static let initialData: [[String]] = [
        ["com.flashforceapp.whitesoxaway", "MLB", "Chicago White Sox", "Away", "0.99", "CCCCCC", "FFFFFF", "000000", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4_2", "", ""],
        ["com.flashforceapp.whitesoxbluered", "MLB", "Chicago White Sox", "Blue/Red Alternate", "0.99", "003366", "CC3333", "FFFFFF", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4_2", "", ""],
        ["com.flashforceapp.whitesoxdefault", "MLB", "Chicago White Sox", "", "0.99", "000000", "C0C0C0", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", "", ""],
        ["com.flashforceapp.oriolesaway", "MLB", "Baltimore Orioles", "Away Gray", "0.99", "A4AAAC", "ed4c09", "000000", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", "", ""],
        ["com.flashforceapp.oriolesorange", "MLB", "Baltimore Orioles", "Orange Alternate", "0.99", "ed4c09", "000000", "FFFFFF", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", "", ""],
        ["com.flashforceapp.oriolesblack", "MLB", "Baltimore Orioles", "Black Alternate", "0.99", "FFFFFF", "ed4c09", "", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4", "", ""],
        ["com.flashforceapp.oriolesdefault", "MLB", "Baltimore Orioles", "", "0.99", "FFFFFF", "ed4c09", "000000", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", "", ""],
        ["com.flashforceapp.dodgersdefault", "MLB", "Los Angeles Dodgers", "", "0.99", "083C6B", "", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6", "", ""],
        ["com.flashforceapp.yankeesdefault", "MLB", "New York Yankees", "", "0.99", "1C2841", "808080", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", "", ""],
        ["com.flashforceapp.diamondbacksdefault", "MLB", "Arizona Diamondbacks", "", "0.99", "A71930", "000000", "DBCEAC", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4_2", "", ""],
        ["com.flashforceapp.rangersdefault", "MLB", "Texas Rangers", "", "0.99", "BD1021", "003279", "", "", "", "", "", "", "", "", "USA", "", "Texas", "6_4", "", ""],
        ["com.flashforceapp.padresdefault", "MLB", "San Diego Padres", "", "0.99", "002147", "B4A76C", "", "", "", "", "", "", "", "", "USA", "San Diego", "California", "6_4", "", ""],
        ["com.flashforceapp.raysdefault", "MLB", "Tampa Bay Rays", "", "0.99", "00285D", "9ECEEE", "ffd700", "", "", "", "", "", "", "", "USA", "Tampa", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.bluejaysdefault", "MLB", "Toronto Blue Jays", "", "0.99", "003DA5", "041E42", "DA291C", "", "", "", "", "", "", "", "Canada", "Toronta", "Ontario", "6_4_2", "", ""],
        ["com.flashforceapp.angelsdefault", "MLB", "Los Angeles Angels of Anaheim", "", "0.99", "B71234", "002244", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", "", ""],
        ["com.flashforceapp.cubsdefault", "MLB", "Chicago Cubs", "", "0.99", "003279", "CC0033", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", "", ""],
        ["com.flashforceapp.rockiesdefault", "MLB", "Colorado Rockies", "", "0.99", "000000", "333366", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Colorado", "6_4_2", "", ""],
        ["com.flashforceapp.astrosdefault", "MLB", "Houston Astros", "", "0.99", "072854", "FF7F00", "", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4", "", ""],
        ["com.flashforceapp.redsoxdefault", "MLB", "Boston Red Sox", "", "0.99", "C60C30", "002244", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", "", ""],
        ["com.flashforceapp.brewersdefault", "MLB", "Milwaukee Brewers", "", "0.99", "182B49", "92754C", "", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", "6_4", "", ""],
        ["com.flashforceapp.indiansdefault", "MLB", "Cleveland Indians", "", "0.99", "003366", "d30335", "", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4", "", ""],
        ["com.flashforceapp.royalsdefault", "MLB", "Kansas City Royals", "", "0.99", "15317E", "74B4FA", "", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", "6_4", "", ""],
        ["com.flashforceapp.stcardinalsdefault", "MLB", "St Louis Cardinals", "", "0.99", "c41e3a", "0A2252", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4", "", ""],
        ["com.flashforceapp.marinersdefault", "MLB", "Seattle Mariners", "", "0.99", "0C2C56", "005C5C", "C0C0C0", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", "", ""],
        ["com.flashforceapp.philliesdefault", "MLB", "Philadelphia Phillies", "", "0.99", "BA0C2F", "003087", "", "", "", "", "", "", "", "", "USA", "Philadephia", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.metsdefault", "MLB", "New York Mets", "", "0.99", "002C77", "FB4F14", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", "", ""],
        ["com.flashforceapp.bravesdefault", "MLB", "Atlanta Braves", "", "0.99", "002F5F", "B71234", "", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4", "", ""],
        ["com.flashforceapp.athleticsdefault", "MLB", "Oakland Athletics", "", "0.99", "003831", "FFD800", "", "", "", "", "", "", "", "", "USA", "Oakland", "California", "6_4", "", ""],
        ["com.flashforceapp.sfgiantsdefault", "MLB", "San Francisco Giants", "", "0.99", "000000", "F2552C", "FFFDD0", "", "", "", "", "", "", "", "USA", "San Francisco", "California", "6_4_2", "", ""],
        ["com.flashforceapp.nationalsdefault", "MLB", "Washington Nationals", "", "0.99", "BA122B", "11225B", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", "", ""],
        ["com.flashforceapp.marlinsdefault", "MLB", "Miami Marlins", "", "0.99", "000000", "F9423A", "8A8D8F", "0077C8", "FFD100", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2_2_2", "", ""],
        ["com.flashforceapp.tigersdefault", "MLB", "Detroit Tigers", "", "0.99", "001742", "DE4406", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4", "", ""],
        ["com.flashforceapp.piratesdefault", "MLB", "Pittsburgh Pirates", "", "0.99", "000000", "fdb829", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.twinsdefault", "MLB", "Minnesota Twins", "", "0.99", "072754", "C6011F", "", "", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4", "", ""],
        ["com.flashforceapp.redsdefault", "MLB", "Cincinnati Reds", "", "0.99", "C6011F", "000000", "", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", "6_4", "", ""],
        ["com.flashforceapp.sharksdefault", "NHL", "San Jose Sharks", "", "0.99", "05535D", "F38F20", "000000", "", "", "", "", "", "", "", "USA", "San Jose", "California", "6_4_2", "", ""],
        ["com.flashforceapp.redwingsdefault", "NHL", "Detroit Red Wings", "", "0.99", "EC1F26", "", "", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6", "", ""],
        ["com.flashforceapp.predatorsdefault", "NHL", "Nashville Predators", "", "0.99", "FDBB2F", "002E62", "", "", "", "", "", "", "", "", "USA", "Nashville", "Tennessee", "6_4", "", ""],
        ["com.flashforceapp.hurricanesdefault", "NHL", "Carolina Hurricanes", "", "0.99", "E03A3E", "000000", "8E8E90", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", "6_4_2", "", ""],
        ["com.flashforceapp.bruinsdefault", "NHL", "Boston Bruins", "", "0.99", "000000", "FFC422", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", "", ""],
        ["com.flashforceapp.bluejacketsdefault", "NHL", "Columbus Blue Jackets", "", "0.99", "00285C", "E03A3E", "A9B0B8", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", "6_4_2", "", ""],
        ["com.flashforceapp.flpanthersdefault", "NHL", "Florida Panthers", "", "0.99", "C8213F", "002E5F", "D59C05", "", "", "", "", "", "", "", "USA", "", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.ducksdefault", "NHL", "Anaheim Ducks", "", "0.99", "000000", "91764B", "EF5225", "", "", "", "", "", "", "", "USA", "Anaheim", "California", "6_4_2", "", ""],
        ["com.flashforceapp.sabresdefault", "NHL", "Buffalo Sabres", "", "0.99", "002E62", "FDBB2F", "AEB6B9", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", "6_4_2", "", ""],
        ["com.flashforceapp.canadiensdefault", "NHL", "Montreal Canadiens", "", "0.99", "BF2F38", "213770", "", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", "6_4", "", ""],
        ["com.flashforceapp.oilsdefault", "NHL", "Edmonton Oilers", "", "0.99", "003777", "E66A20", "", "", "", "", "", "", "", "", "Canada", "Edmonton", "Alberta", "6_4", "", ""],
        ["com.flashforceapp.pengiunsdefault", "NHL", "Pittsburgh Penguins", "", "0.99", "000000", "D1BD80", "", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.nyrangersdefault", "NHL", "New York Rangers", "", "0.99", "0161AB", "E6393F", "", "", "", "", "", "", "", "", "USA", "New York", "New York", "6_4", "", ""],
        ["com.flashforceapp.capitalsdefault", "NHL", "Washington Capitals", "", "0.99", "CF132B", "00214E", "000000", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4_2", "", ""],
        ["com.flashforceapp.bluesdefault", "NHL", "St Louis Blues", "", "0.99", "0546A0", "FFC325", "101F48", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4_2", "", ""],
        ["com.flashforceapp.mapleleafsdefault", "NHL", "Toronto Maple Leafs", "", "0.99", "003777", "", "", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6", "", ""],
        ["com.flashforceapp.wilddefault", "NHL", "Minnesota Wild", "", "0.99", "025736", "BF2B37", "EFB410", "EEE3C7", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4_2_2", "", ""],
        ["com.flashforceapp.starsdefault", "NHL", "Dallas Stars", "", "0.99", "006A4E", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", "", ""],
        ["com.flashforceapp.wjetsdefault", "NHL", "Winnipeg Jets", "", "0.99", "002E62", "0168AB", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Winnipeg", "Manitoba", "6_4_2", "", ""],
        ["com.flashforceapp.devilsdefault", "NHL", "New Jersey Devils", "", "0.99", "E03A3E", "000000", "", "", "", "", "", "", "", "", "USA", "", "New Jersey", "6_4", "", ""],
        ["com.flashforceapp.lightningdefault", "NHL", "Tampa Bay Lightning", "", "0.99", "013E7D", "000000", "C0C0C0", "", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.kingsdefault", "NHL", "Los Angeles Kings", "", "0.99", "000000", "AFB7BA", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", "", ""],
        ["com.flashforceapp.flamesdefault", "NHL", "Calgary Flames", "", "0.99", "E03A3E", "FFC758", "000000", "", "", "", "", "", "", "", "Canada", "Calgary", "Alberta", "6_4_2", "", ""],
        ["com.flashforceapp.blackhawksdefault", "NHL", "Chicago Blackhawks", "", "0.99", "E3263A", "000000", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", "", ""],
        ["com.flashforceapp.avalancedefault", "NHL", "Colorado Avalanche", "", "0.99", "8B2942", "01548A", "000000", "A9B0B8", "", "", "", "", "", "", "USA", "", "Colorado", "6_4_2_2", "", ""],
        ["com.flashforceapp.coyotesdefault", "NHL", "Arizona Coyotes", "", "0.99", "841F27", "000000", "EFE1C6", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4_2", "", ""],
        ["com.flashforceapp.senatorsdefault", "NHL", "Ottawa Senators", "", "0.99", "E4173E", "000000", "D69F0F", "", "", "", "", "", "", "", "Canada", "Ottawa", "Ontario", "6_4_2", "", ""],
        ["com.flashforceapp.islandersdefault", "NHL", "New York Islanders", "", "0.99", "00529B", "F57D31", "", "", "", "", "", "", "", "", "USA", "", "New York", "6_4", "", ""],
        ["com.flashforceapp.canucksdefault", "NHL", "Vancouver Canucks", "", "0.99", "07346F", "047A4A", "A8A9AD", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", "6_4_2", "", ""],
        ["com.flashforceapp.flyersdefault", "NHL", "Philadelphia Flyers", "", "0.99", "F47940", "000000", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.saintsdefault", "NFL", "New Orleans Saints", "", "0.99", "000000", "D2B887", "FFFFFF", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", "6_4", "", ""],
        ["com.flashforceapp.bearsdefault", "NFL", "Chicago Bears", "", "0.99", "03202F", "DD4814", "FFFFFF", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", "", ""],
        ["com.flashforceapp.steelersdefault", "NFL", "Pittsburgh Steelers", "", "0.99", "000000", "F2C800", "FFFFFF", "", "", "", "", "", "", "", "USA", "Pittsburgh", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.patriotsdefault", "NFL", "New England Patriots", "", "0.99", "0D254C", "D6D6D6", "C80815", "FFFFFF", "", "", "", "", "", "", "USA", "New England", "", "6_4_2", "", ""],
        ["com.flashforceapp.jetsdefault", "NFL", "New York Jets", "", "0.99", "0C371D", "FFFFFF", "", "", "", "", "", "", "", "", "USA", "", "New York", "6", "", ""],
        ["com.flashforceapp.panthersdefault", "NFL", "Carolina Panthers", "", "0.99", "000000", "0088CE", "A5ACAF", "", "", "", "", "", "", "", "USA", "Carolina", "", "6_4_2", "", ""],
        ["com.flashforceapp.fortyninersdefault", "NFL", "San Francisco 49ers", "", "0.99", "AF1E2C", "E6BE8A", "FFFFFF", "000000", "", "", "", "", "", "", "USA", "San Francisco", "California", "6_4_2", "", ""],
        ["com.flashforceapp.buccaneersdefault", "NFL", "Tampa Bay Buccaneers", "", "0.99", "D60A0B", "89765F", "000000", "FF7A00", "", "", "", "", "", "", "USA", "Tampa Bay", "Florida", "6_4_2_2", "", ""],
        ["com.flashforceapp.eaglesdefault", "NFL", "Philadelphia Eagles", "", "0.99", "003B48", "000000", "708090", "C0C0C0", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4_2_2", "", ""],
        ["com.flashforceapp.coltsdefault", "NFL", "Indianapolis Colts", "", "0.99", "003B7B", "FFFFFF", "", "", "", "", "", "", "", "", "USA", "Indianapolis", "Indiana", "6", "", ""],
        ["com.flashforceapp.seahawksdefault", "NFL", "Seattle Seahawks", "", "0.99", "06192E", "4EAE47", "ACB6BC", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", "", ""],
        ["com.flashforceapp.cardinalsalt", "NFL", "Arizona Cardinals", "Alternate", "0.99", "111C24", "97233F", "", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4", "", ""],
        ["com.flashforceapp.cardinalsdefault", "NFL", "Arizona Cardinals", "", "0.99", "870619", "000000", "", "", "", "", "", "", "", "", "USA", "", "Arizona", "6_4", "", ""],
        ["com.flashforceapp.falconsdefault", "NFL", "Atlanta Falcons", "", "0.99", "BD0D18", "000000", "DCE0E5", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4_2", "", ""],
        ["com.flashforceapp.texansdefault", "NFL", "Houston Texans", "", "0.99", "02253A", "B31B34", "FFFFFF", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4", "", ""],
        ["com.flashforceapp.titansdefault", "NFL", "Tennessee Titans", "", "0.99", "648FCC", "000080", "FF0000", "C0C0C0", "FFFFFF", "", "", "", "", "", "USA", "", "Tennessee", "6_4_2_2", "", ""],
        ["com.flashforceapp.brownsdefault", "NFL", "Cleveland Browns", "", "0.99", "26201E", "E34912", "FFFFFF", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4", "", ""],
        ["com.flashforceapp.bengalsdefault", "NFL", "Cincinnati Bengals", "", "0.99", "000000", "FB4F14", "FFFFFF", "", "", "", "", "", "", "", "USA", "Cincinatti", "Ohio", "6_4", "", ""],
        ["com.flashforceapp.raidersdefault", "NFL", "Oakland Raiders", "", "0.99", "C4C8CB", "000000", "FFFFFF", "", "", "", "", "", "", "", "USA", "Oakland", "California", "6_4", "", ""],
        ["com.flashforceapp.billsdefault", "NFL", "Buffalo Bills", "", "0.99", "00338D", "C60C30", "", "", "", "", "", "", "", "", "USA", "Buffalo", "New York", "6_4", "", ""],
        ["com.flashforceapp.chargersdefault", "NFL", "San Diego Chargers", "", "0.99", "08214A", "EEC607", "FFFFFF", "", "", "", "", "", "", "", "USA", "San Diego", "California", "6_4_2_2", "", ""],
        ["com.flashforceapp.dolphicsdefault", "NFL", "Miami Dolphins", "", "0.99", "008d97", "015679", "F5811F", "FFFFFF", "", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.giantsdefault", "NFL", "New York Giants", "", "0.99", "192F6B", "FFFFFF", "808080", "CA001A", "", "", "", "", "", "", "USA", "", "New York", "6_4_2", "", ""],
        ["com.flashforceapp.ramsdefault", "NFL", "St Louis Rams", "", "0.99", "13264B", "C9AF74", "", "", "", "", "", "", "", "", "USA", "St Louis", "Missouri", "6_4", "", ""],
        ["com.flashforceapp.jaguarsdefault", "NFL", "Jacksonville Jaguars", "", "0.99", "000000", "D0B239", "007198", "FFFFFF", "", "", "", "", "", "", "USA", "Jacksonville", "Mississippi", "6_4_2", "", ""],
        ["com.flashforceapp.ravensdefault", "NFL", "Baltimore Ravens", "", "0.99", "280353", "000000", "D0B240", "", "", "", "", "", "", "", "USA", "Baltimore", "Maryland", "6_4_2", "", ""],
        ["com.flashforceapp.lionsdefault", "NFL", "Detroit Lions", "", "0.99", "006DB0", "C5C7CF", "000000", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4_2", "", ""],
        ["com.flashforceapp.chiefsdefault", "NFL", "Kansas City Chiefs", "", "0.99", "B20032", "F2C800", "FFFFFF", "", "", "", "", "", "", "", "USA", "Kansas City", "Missouri", "6_4", "", ""],
        ["com.flashforceapp.broncosdefault", "NFL", "Denver Broncos", "", "0.99", "FB4F14", "002244", "FFFFFF", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4", "", ""],
        ["com.flashforceapp.redskinsdefault", "NFL", "Washington Redskins", "", "0.99", "773141", "FFB612", "FFFFFF", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", "", ""],
        ["com.flashforceapp.packersdefault", "NFL", "Green Bay Packers", "", "0.99", "213D30", "FFCC00", "FFFFFF", "", "", "", "", "", "", "", "USA", "Green Bay", "Wisconsin", "6_4", "", ""],
        ["com.flashforceapp.vikingsdefault", "NFL", "Minnesota Vikings", "", "0.99", "4F2682", "FFC52F", "FFFFFF", "", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4", "", ""],
        ["com.flashforceapp.cowboysdefault", "NFL", "Dallas Cowboys", "", "0.99", "002244", "8C8B8A", "", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4", "", ""],
        ["com.flashforceapp.firedefault", "MLS", "Chicago Fire", "", "0.99", "AF2626", "0A174A", "8A8D8F", "", "", "", "", "", "", "", "USA", "Chiago", "Illinois", "6_4_2", "", ""],
        ["com.flashforceapp.revolutiondefault", "MLS", "New England Revolution", "", "0.99", "0A2141", "D80016", "8A8D8F", "", "", "", "", "", "", "", "USA", "New England", "", "6_4_2", "", ""],
        ["com.flashforceapp.torontofcdefault", "MLS", "Toronto FC", "", "0.99", "D80016", "313F49", "A1AAAD", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6_4_2", "", ""],
        ["com.flashforceapp.fcdallasdefault", "MLS", "FC Dallas", "", "0.99", "CF0032", "07175C", "8A8D8F", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", "", ""],
        ["com.flashforceapp.timbersdefault", "MLS", "Portland Timbers", "", "0.99", "004812", "EBE72B", "", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", "6_4", "", ""],
        ["com.flashforceapp.nycfcdefault", "MLS", "New York City FC", "", "0.99", "6CADDF", "00285E", "FD4F00", "", "", "", "", "", "", "", "USA", "New York", "", "6_4_2", "", ""],
        ["com.flashforceapp.redbullsdefault", "MLS", "New York Red Bulls", "", "0.99", "D50031", "012055", "FFC800", "8A8D8F", "", "", "", "", "", "", "USA", "New York", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.impactdefault", "MLS", "Montreal Impact", "", "0.99", "122089", "000000", "7A878F", "", "", "", "", "", "", "", "Canada", "Montreal", "Quebec", "6_4_2", "", ""],
        ["com.flashforceapp.dcuniteddefault", "MLS", "DC United", "", "0.99", "000000", "DD0000", "", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4", "", ""],
        ["com.flashforceapp.crewdefault", "MLS", "Columbus Crew", "", "0.99", "000000", "FFDB00", "8A8D8F", "", "", "", "", "", "", "", "USA", "Columbus", "Ohio", "6_4_2", "", ""],
        ["com.flashforceapp.earthquakesdefault", "MLS", "San Jose Earthquakes", "", "0.99", "0051BA", "000000", "B1B4B2", "", "", "", "", "", "", "", "USA", "San Jose", "California", "6_4_2", "", ""],
        ["com.flashforceapp.uniondefault", "MLS", "Philadelphia Union", "", "0.99", "001B2D", "B18500", "348AE1", "", "", "", "", "", "", "", "USA", "", "Philadelphia", "6_4_2", "", ""],
        ["com.flashforceapp.rapidsdefault", "MLS", "Colorado Rapids", "", "0.99", "91022D", "85B7EA", "8A8D8F", "313F49", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4_2_2", "", ""],
        ["com.flashforceapp.sportingkcdefault", "MLS", "Sporting Kansas City", "", "0.99", "A4BBD7", "0A2141", "787775", "", "", "", "", "", "", "", "USA", "Kansas City", "Kansas", "6_4_2", "", ""],
        ["com.flashforceapp.soundersfcdefault", "MLS", "Seattle Sounders FC", "", "0.99", "4F8A10", "11568C", "212930", "", "", "", "", "", "", "", "USA", "Seattle", "Washington", "6_4_2", "", ""],
        ["com.flashforceapp.chivasusadefault", "MLS", "Chivas USA", "", "0.99", "AA002C", "031A43", "FFC800", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4_2", "", ""],
        ["com.flashforceapp.orlandoscdefault", "MLS", "Orlando City SC", "", "0.99", "633492", "FDE192", "", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", "6_4", "", ""],
        ["com.flashforceapp.realsldefault", "MLS", "Real Salt Lake", "", "0.99", "A50531", "013474", "F2D11A", "", "", "", "", "", "", "", "USA", "Salt Lake", "Utah", "6_4_2", "", ""],
        ["com.flashforceapp.whitecapsfcdefault", "MLS", "Vancouver Whitecaps FC", "", "0.99", "12264C", "85B7EA", "838383", "", "", "", "", "", "", "", "Canada", "Vancouver", "British Columbia", "6_4_2", "", ""],
        ["com.flashforceapp.dynamodefault", "MLS", "Houston Dynamo", "", "0.99", "F36600", "2E2926", "85B7EA", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4_2", "", ""],
        ["com.flashforceapp.lagalaxydefault", "MLS", "Los Angeles Galaxy", "", "0.99", "00245D", "004689", "F1AA00", "FFD200", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4_2_2", "", ""],
        ["com.flashforceapp.southamptondefault", "EPL", "Southampton", "", "0.99", "ED1A3B", "211E1F", "FFC20E", "", "", "", "", "", "", "", "UK", "Southampton", "England", "6_4_2", "", ""],
        ["com.flashforceapp.manchuniteddefault", "EPL", "Manchester United", "", "0.99", "DA020E", "FFE500", "000000", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4_2", "", ""],
        ["com.flashforceapp.liverpoolepldefault", "EPL", "Liverpool", "", "0.99", "00A398", "D00027", "FEF667", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4_2", "", ""],
        ["com.flashforceapp.stokecityepldefault", "EPL", "Stoke City", "", "0.99", "E03A3E", "1B449C", "", "", "", "", "", "", "", "", "UK", "Stoke", "England", "6_4", "", ""],
        ["com.flashforceapp.hotspurdefault", "EPL", "Tottenham Hotspur", "", "0.99", "001C58", "", "", "", "", "", "", "", "", "", "UK", "Tottenham", "England", "6", "", ""],
        ["com.flashforceapp.burnleydefault", "EPL", "Burnley", "", "0.99", "8CCCE5", "53162F", "F9EC34", "", "", "", "", "", "", "", "UK", "Burnley", "England", "6_4_2", "", ""],
        ["com.flashforceapp.westhamdefault", "EPL", "West Ham United", "", "0.99", "60223B", "F7C240", "5299C6", "", "", "", "", "", "", "", "UK", "West Ham", "England", "6_4_2", "", ""],
        ["com.flashforceapp.astonvilladefault", "EPL", "Aston Villa", "", "0.99", "94BEE5", "7A003C", "FFE600", "", "", "", "", "", "", "", "UK", "Witton", "England", "6_4_2", "", ""],
        ["com.flashforceapp.swanseadefault", "EPL", "Swansea City", "", "0.99", "000000", "", "", "", "", "", "", "", "", "", "UK", "Swansea", "Wales", "6", "", ""],
        ["com.flashforceapp.arsenaldefault", "EPL", "Arsenal", "", "0.99", "EF0107", "023474", "9C824A", "", "", "", "", "", "", "", "UK", "Holloway", "England", "6_4_2", "", ""],
        ["com.flashforceapp.crystalpalacedefault", "EPL", "Crystal Palace", "", "0.99", "1B458F", "C4122E", "A7A5A6", "", "", "", "", "", "", "", "UK", "South Norwood", "England", "6_4_2", "", ""],
        ["com.flashforceapp.bromwichalbiondefault", "EPL", "West Bromwich Albion", "", "0.99", "091453", "", "", "", "", "", "", "", "", "", "UK", "West Bromwich", "England", "6", "", ""],
        ["com.flashforceapp.parkrangersdefault", "EPL", "Queens Park Rangers", "", "0.99", "005CAB", "", "", "", "", "", "", "", "", "", "UK", "Queens Park", "England", "6", "", ""],
        ["com.flashforceapp.newcastleuniteddefault", "EPL", "Newcastle United", "", "0.99", "00B6F1", "BBBDBF", "231F20", "F0B83D", "", "", "", "", "", "", "UK", "Newcastle", "England", "6_4_2_2", "", ""],
        ["com.flashforceapp.evertonepldefault", "EPL", "Everton", "", "0.99", "274488", "", "", "", "", "", "", "", "", "", "UK", "Liverpool", "England", "6", "", ""],
        ["com.flashforceapp.hullcityepldefault", "EPL", "Hull City", "", "0.99", "F5A12D", "000000", "", "", "", "", "", "", "", "", "UK", "Yorkshire", "England", "6_4", "", ""],
        ["com.flashforceapp.chelseaepldefault", "EPL", "Chelsea", "", "0.99", "034694", "DBA111", "ED1C24", "", "", "", "", "", "", "", "UK", "Chelsea", "England", "6_4_2", "", ""],
        ["com.flashforceapp.leicesterepldefault", "EPL", "Leicester City", "", "0.99", "FDBE11", "0053A0", "", "", "", "", "", "", "", "", "UK", "Leicester", "England", "6_4", "", ""],
        ["com.flashforceapp.sunderlandepldefault", "EPL", "Sunderland", "", "0.99", "EB172B", "A68A26", "211E1E", "", "", "", "", "", "", "", "UK", "Sunderland", "England", "6_4_2", "", ""],
        ["com.flashforceapp.manchesterepldefault", "EPL", "Manchester City", "", "0.99", "5CBFEB", "FFCE65", "", "", "", "", "", "", "", "", "UK", "Manchester", "England", "6_4", "", ""],
        ["com.flashforceapp.knicksdefault", "NBA", "New York Knicks", "", "0.99", "0953A0", "FF7518", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "New York", "6_4_2", "", ""],
        ["com.flashforceapp.lakersdefault", "NBA", "Los Angeles Lakers", "", "0.99", "4A2583", "F5AF1B", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", "", ""],
        ["com.flashforceapp.grizzliesdefault", "NBA", "Memphis Grizzlies", "", "0.99", "001F70", "7399C6", "BED4E9", "FDB927", "", "", "", "", "", "", "USA", "Memphis", "Tennessee", "6_4_2_2", "", ""],
        ["com.flashforceapp.spursdefault", "NBA", "San Antonio Spurs", "", "0.99", "000000", "BEC8C9", "", "", "", "", "", "", "", "", "USA", "San Antonio", "Texas", "6_4", "", ""],
        ["com.flashforceapp.pelicansdefault", "NBA", "New Orleans Pelicans", "", "0.99", "002B5C", "B4975A", "E31836", "", "", "", "", "", "", "", "USA", "New Orleans", "Louisiana", "6_4_2", "", ""],
        ["com.flashforceapp.rocketsdefault", "NBA", "Houston Rockets", "", "0.99", "CE1138", "CCCCCC", "000000", "", "", "", "", "", "", "", "USA", "Houston", "Texas", "6_4_2", "", ""],
        ["com.flashforceapp.pistonsdefault", "NBA", "Detroit Pistons", "", "0.99", "00519A", "EB003C", "041e40", "", "", "", "", "", "", "", "USA", "Detroit", "Michigan", "6_4_2", "", ""],
        ["com.flashforceapp.celticsdefault", "NBA", "Boston Celtics", "", "0.99", "FFFFFF", "009E60", "", "", "", "", "", "", "", "", "USA", "Boston", "Massachusetts", "6_4", "", ""],
        ["com.flashforceapp.heatdefault", "NBA", "Miami Heat", "", "0.99", "000000", "B62630", "FF9F00", "", "", "", "", "", "", "", "USA", "Miami", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.magicdefault", "NBA", "Orlando Magic", "", "0.99", "0047AB", "000000", "708090", "", "", "", "", "", "", "", "USA", "Orlando", "Florida", "6_4_2", "", ""],
        ["com.flashforceapp.trailblazersdefault", "NBA", "Portland Trail Blazers", "", "0.99", "F0163A", "B6BFBF", "000000", "", "", "", "", "", "", "", "USA", "Portland", "Oregon", "6_4_2", "", ""],
        ["com.flashforceapp.warriorsdefault", "NBA", "Golden State Warriors", "", "0.99", "04529C", "FFCC33", "", "", "", "", "", "", "", "", "USA", "Golden State", "California", "6_4", "", ""],
        ["com.flashforceapp.bullsdefault", "NBA", "Chicago Bulls", "", "0.99", "FFFFFF", "D4001F", "", "", "", "", "", "", "", "", "USA", "Chicago", "Illinois", "6_4", "", ""],
        ["com.flashforceapp.wizardsdefault", "NBA", "Washington Wizards", "", "0.99", "002B5C", "E31837", "C4CDD4", "", "", "", "", "", "", "", "USA", "Washington", "DC", "6_4_2", "", ""],
        ["com.flashforceapp.mavericksdefault", "NBA", "Dallas Mavericks", "", "0.99", "0b60AD", "072156", "A9A9A9", "", "", "", "", "", "", "", "USA", "Dallas", "Texas", "6_4_2", "", ""],
        ["com.flashforceapp.timerwolvesdefault", "NBA", "Minnesota Timberwolves", "", "0.99", "0F4D92", "000000", "8C92AC", "50C878", "", "", "", "", "", "", "USA", "", "Minnesota", "6_4_2_2", "", ""],
        ["com.flashforceapp.clippersdefault", "NBA", "Los Angeles Clippers", "", "0.99", "EE2944", "146AA2", "", "", "", "", "", "", "", "", "USA", "Los Angeles", "California", "6_4", "", ""],
        ["com.flashforceapp.thunderdefault", "NBA", "Oklahoma City Thunder", "", "0.99", "007DC3", "F05133", "FDBB30", "002D62", "", "", "", "", "", "", "USA", "Oklahoma City", "Oklahoma", "6_4_2_2", "", ""],
        ["com.flashforceapp.hornetsdefault", "NBA", "Charlotte Hornets", "", "0.99", "FFFFFF", "008CA8", "1D1160", "", "", "", "", "", "", "", "USA", "Charlotte", "North Carolina", "6_4_2", "", ""],
        ["com.flashforceapp.bucksdefault", "NBA", "Milwaukee Bucks", "", "0.99", "003614", "E32636", "C0C0C0", "", "", "", "", "", "", "", "USA", "Milwaukee", "Wisconsin", "6_4_2", "", ""],
        ["com.flashforceapp.raptorsdefault", "NBA", "Toronto Raptors", "", "0.99", "B31B1B", "000000", "708090", "", "", "", "", "", "", "", "Canada", "Toronto", "Ontario", "6_4_2", "", ""],
        ["com.flashforceapp.jazzdefault", "NBA", "Utah Jazz", "", "0.99", "00275D", "FF9100", "0D4006", "B5B5B5", "", "", "", "", "", "", "USA", "", "Utah", "6_4_2_2", "", ""],
        ["com.flashforceapp.sunsdefault", "NBA", "Phoenix Suns", "", "0.99", "1C105E", "E65F20", "000000", "B1B3B3", "", "", "", "", "", "", "USA", "Phoenix", "Arizona", "6_4_2_2", "", ""],
        ["com.flashforceapp.sackingsdefault", "NBA", "Sacramento Kings", "", "0.99", "753BBD", "000000", "8A8D8F", "", "", "", "", "", "", "", "USA", "Sacramento", "California", "6_4_2", "", ""],
        ["com.flashforceapp.sevsixersdefault", "NBA", "Philadelphia 76ers", "", "0.99", "0046AD", "D0103A", "", "", "", "", "", "", "", "", "USA", "Philadelphia", "Pennsylvania", "6_4", "", ""],
        ["com.flashforceapp.cavaliersdefault", "NBA", "Cleveland Cavaliers", "", "0.99", "FFFFFF", "860038", "FDBB30", "", "", "", "", "", "", "", "USA", "Cleveland", "Ohio", "6_4_2", "", ""],
        ["com.flashforceapp.hawksdefault", "NBA", "Atlanta Hawks", "", "0.99", "FFFFFF", "FF0000", "BED600", "", "", "", "", "", "", "", "USA", "Atlanta", "Georgia", "6_4_2", "", ""],
        ["com.flashforceapp.netsdefault", "NBA", "Brooklyn Nets", "", "0.99", "FFFFFF", "000000", "", "", "", "", "", "", "", "", "USA", "Brooklyn", "New York", "6", "", ""],
        ["com.flashforceapp.pacersdefault", "NBA", "Indiana Pacers", "", "0.99", "092C57", "FFC322", "C0C0C0", "", "", "", "", "", "", "", "USA", "", "Indiana", "6_4_2", "", ""],
        ["com.flashforceapp.nuggetsdefault", "NBA", "Denver Nuggets", "", "0.99", "4b90CD", "FDB827", "002D62", "", "", "", "", "", "", "", "USA", "Denver", "Colorado", "6_4_2", "", ""],
        ["com.flashforceapp.afghanistan", "National Soccer", "Afghanistan", "", "0.99", "bf0000", "009900", "000000", "", "", "", "", "", "", "", "Afghanistan", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.australia", "National Soccer", "Australia", "", "0.99", "fcd116", "008751", "ffffff", "", "", "", "", "", "", "", "Australia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.bahrain", "National Soccer", "Bahrain", "", "0.99", "ce1126", "ffffff", "", "", "", "", "", "", "", "", "Bahrain", "", "", "6_4", "", ""],
        ["com.flashforceapp.bangladesh", "National Soccer", "Bangladesh", "", "0.99", "006a4e", "f42a41", "", "", "", "", "", "", "", "", "Bangladesh", "", "", "6_4", "", ""],
        ["com.flashforceapp.bhutan", "National Soccer", "Bhutan", "", "0.99", "ff4e12", "ffd520", "", "", "", "", "", "", "", "", "Bhutan", "", "", "6_4", "", ""],
        ["com.flashforceapp.bruneidarussalam", "National Soccer", "Brunei Darussalam", "", "0.99", "f7e017", "000000", "ffffff", "", "", "", "", "", "", "", "Brunei Darussalam", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.cambodia", "National Soccer", "Cambodia", "", "0.99", "e00025", "032ea1", "ffffff", "", "", "", "", "", "", "", "Cambodia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.chinapr", "National Soccer", "China PR", "", "0.99", "ffffff", "de2910", "", "", "", "", "", "", "", "", "China PR", "", "", "6_4", "", ""],
        ["com.flashforceapp.chinesetaipei", "National Soccer", "Chinese Taipei", "", "0.99", "000095", "ffffff", "fe0000", "", "", "", "", "", "", "", "Chinese Taipei", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.guam", "National Soccer", "Guam", "", "0.99", "00297b", "ffffff", "", "", "", "", "", "", "", "", "Guam", "", "", "6_4", "", ""],
        ["com.flashforceapp.hongkong", "National Soccer", "Hong Kong", "", "0.99", "de2910", "ffffff", "", "", "", "", "", "", "", "", "Hong Kong", "", "", "6_4", "", ""],
        ["com.flashforceapp.india", "National Soccer", "India", "", "0.99", "000088", "ffffff", "", "", "", "", "", "", "", "", "India", "", "", "6_4", "", ""],
        ["com.flashforceapp.indonesia", "National Soccer", "Indonesia", "", "0.99", "ce1126", "ffffff", "", "", "", "", "", "", "", "", "Indonesia", "", "", "6_4", "", ""],
        ["com.flashforceapp.iran", "National Soccer", "Iran", "", "0.99", "ffffff", "da0000", "239f40", "", "", "", "", "", "", "", "Iran", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.iraq", "National Soccer", "Iraq", "", "0.99", "007a3d", "000000", "ffffff", "", "", "", "", "", "", "", "Iraq", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.japan", "National Soccer", "Japan", "", "0.99", "ffffff", "bc002d", "", "", "", "", "", "", "", "", "Japan", "", "", "6_4", "", ""],
        ["com.flashforceapp.jordan", "National Soccer", "Jordan", "", "0.99", "ffffff", "ce1126", "", "", "", "", "", "", "", "", "Jordan", "", "", "6_4", "", ""],
        ["com.flashforceapp.koreadpr", "National Soccer", "Korea DPR", "", "0.99", "ed1c27", "024fa2", "ffffff", "", "", "", "", "", "", "", "Korea DPR", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.korearepublic", "National Soccer", "Korea Republic", "", "0.99", "c60c30", "003478", "", "", "", "", "", "", "", "", "Korea Republic", "", "", "6_4", "", ""],
        ["com.flashforceapp.kuwait", "National Soccer", "Kuwait", "", "0.99", "007a3d", "ffffff", "", "", "", "", "", "", "", "", "Kuwait", "", "", "6_4", "", ""],
        ["com.flashforceapp.kyrgyzstan", "National Soccer", "Kyrgyzstan", "", "0.99", "e8112d", "ffef00", "", "", "", "", "", "", "", "", "Kyrgyzstan", "", "", "6_4", "", ""],
        ["com.flashforceapp.laos", "National Soccer", "Laos", "", "0.99", "002868", "ffffff", "ce1126", "", "", "", "", "", "", "", "Laos", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.lebanon", "National Soccer", "Lebanon", "", "0.99", "ed1c24", "00a651", "ffffff", "", "", "", "", "", "", "", "Lebanon", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.macau", "National Soccer", "Macau", "", "0.99", "00785e", "ffffff", "", "", "", "", "", "", "", "", "Macau", "", "", "6_4", "", ""],
        ["com.flashforceapp.malaysia", "National Soccer", "Malaysia", "", "0.99", "000000", "ffcc00", "", "", "", "", "", "", "", "", "Malaysia", "", "", "6_4", "", ""],
        ["com.flashforceapp.maldives", "National Soccer", "Maldives", "", "0.99", "d21034", "ffffff", "007e3a", "", "", "", "", "", "", "", "Maldives", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.mongolia", "National Soccer", "Mongolia", "", "0.99", "C4272F", "015197", "F9CF02", "", "", "", "", "", "", "", "Mongolia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.myanmar", "National Soccer", "Myanmar", "", "0.99", "ea2839", "ffffff", "", "", "", "", "", "", "", "", "Myanmar", "", "", "6_4", "", ""],
        ["com.flashforceapp.nepal", "National Soccer", "Nepal", "", "0.99", "dc143c", "ffffff", "", "", "", "", "", "", "", "", "Nepal", "", "", "6_4", "", ""],
        ["com.flashforceapp.northernmarianaislands", "National Soccer", "Northern Mariana Islands", "", "0.99", "0071bc", "ffffff", "", "", "", "", "", "", "", "", "Northern Mariana Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.oman", "National Soccer", "Oman", "", "0.99", "db161b", "ffffff", "", "", "", "", "", "", "", "", "Oman", "", "", "6_4", "", ""],
        ["com.flashforceapp.pakistan", "National Soccer", "Pakistan", "", "0.99", "01411c", "ffffff", "", "", "", "", "", "", "", "", "Pakistan", "", "", "6_4", "", ""],
        ["com.flashforceapp.palestine", "National Soccer", "Palestine", "", "0.99", "ce1126", "ffffff", "", "", "", "", "", "", "", "", "Palestine", "", "", "6_4", "", ""],
        ["com.flashforceapp.philippines", "National Soccer", "Philippines", "", "0.99", "0038a8", "ffffff", "", "", "", "", "", "", "", "", "Philippines", "", "", "6_4", "", ""],
        ["com.flashforceapp.qatar", "National Soccer", "Qatar", "", "0.99", "8d1b3d", "ffffff", "", "", "", "", "", "", "", "", "Qatar", "", "", "6_4", "", ""],
        ["com.flashforceapp.saudiarabia", "National Soccer", "Saudi Arabia", "", "0.99", "006c35", "ffffff", "", "", "", "", "", "", "", "", "Saudi Arabia", "", "", "6_4", "", ""],
        ["com.flashforceapp.singapore", "National Soccer", "Singapore", "", "0.99", "ED2939", "000000", "", "", "", "", "", "", "", "", "Singapore", "", "", "6_4", "", ""],
        ["com.flashforceapp.srilanka", "National Soccer", "Sri Lanka", "", "0.99", "ffb700", "8d2029", "", "", "", "", "", "", "", "", "Sri Lanka", "", "", "6_4", "", ""],
        ["com.flashforceapp.syria", "National Soccer", "Syria", "", "0.99", "ce1126", "ffffff", "", "", "", "", "", "", "", "", "Syria", "", "", "6_4", "", ""],
        ["com.flashforceapp.tajikistan", "National Soccer", "Tajikistan", "", "0.99", "cc0000", "ffffff", "", "", "", "", "", "", "", "", "Tajikistan", "", "", "6_4", "", ""],
        ["com.flashforceapp.thailand", "National Soccer", "Thailand", "", "0.99", "241d4f", "ffffff", "", "", "", "", "", "", "", "", "Thailand", "", "", "6_4", "", ""],
        ["com.flashforceapp.timor-leste", "National Soccer", "Timor-Leste", "", "0.99", "dc241f", "000000", "ffc726", "", "", "", "", "", "", "", "Timor-Leste", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.turkmenistan", "National Soccer", "Turkmenistan", "", "0.99", "28ae66", "ffffff", "", "", "", "", "", "", "", "", "Turkmenistan", "", "", "6_4", "", ""],
        ["com.flashforceapp.unitedarabemirates", "National Soccer", "United Arab Emirates", "", "0.99", "ff0000", "ffffff", "", "", "", "", "", "", "", "", "United Arab Emirates", "", "", "6_4", "", ""],
        ["com.flashforceapp.uzbekistan", "National Soccer", "Uzbekistan", "", "0.99", "0099b5", "ffffff", "", "", "", "", "", "", "", "", "Uzbekistan", "", "", "6_4", "", ""],
        ["com.flashforceapp.vietnam", "National Soccer", "Vietnam", "", "0.99", "DA251D", "FFFF00", "", "", "", "", "", "", "", "", "Vietnam", "", "", "6_4", "", ""],
        ["com.flashforceapp.yemen", "National Soccer", "Yemen", "", "0.99", "ce1126", "ffffff", "000000", "", "", "", "", "", "", "", "Yemen", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.algeria", "National Soccer", "Algeria", "", "0.99", "ffffff", "006233", "", "", "", "", "", "", "", "", "Algeria", "", "", "6_4", "", ""],
        ["com.flashforceapp.angola", "National Soccer", "Angola", "", "0.99", "ce1126", "000000", "f9d616", "", "", "", "", "", "", "", "Angola", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.benin", "National Soccer", "Benin", "", "0.99", "fcd116", "e8112d", "008751", "", "", "", "", "", "", "", "Benin", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.botswana", "National Soccer", "Botswana", "", "0.99", "75aadb", "000000", "ffffff", "", "", "", "", "", "", "", "Botswana", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.burkinafaso", "National Soccer", "Burkina Faso", "", "0.99", "009e49", "ef2b2d", "", "", "", "", "", "", "", "", "Burkina Faso", "", "", "6_4", "", ""],
        ["com.flashforceapp.burundi", "National Soccer", "Burundi", "", "0.99", "ce1126", "ffffff", "1eb53a", "", "", "", "", "", "", "", "Burundi", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.cameroon", "National Soccer", "Cameroon", "", "0.99", "007a5e", "ce1126", "fcd116", "", "", "", "", "", "", "", "Cameroon", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.capeverde", "National Soccer", "Cape Verde", "", "0.99", "003893", "ffffff", "cf2027", "", "", "", "", "", "", "", "Cape Verde", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.centralafricanrepublic", "National Soccer", "Central African Republic", "", "0.99", "ffffff", "003082", "", "", "", "", "", "", "", "", "Central African Republic", "", "", "6_4", "", ""],
        ["com.flashforceapp.chad", "National Soccer", "Chad", "", "0.99", "002664", "fecb00", "c60c30", "", "", "", "", "", "", "", "Chad", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.comoros", "National Soccer", "Comoros", "", "0.99", "ffffff", "3d8e33", "", "", "", "", "", "", "", "", "Comoros", "", "", "6_4", "", ""],
        ["com.flashforceapp.congo", "National Soccer", "Congo", "", "0.99", "dc241f", "ffffff", "", "", "", "", "", "", "", "", "Congo", "", "", "6_4", "", ""],
        ["com.flashforceapp.congodr", "National Soccer", "Congo DR", "", "0.99", "007fff", "ce1021", "", "", "", "", "", "", "", "", "Congo DR", "", "", "6_4", "", ""],
        ["com.flashforceapp.djibouti", "National Soccer", "Djibouti", "", "0.99", "ffffff", "12ad2b", "", "", "", "", "", "", "", "", "Djibouti", "", "", "6_4", "", ""],
        ["com.flashforceapp.egypt", "National Soccer", "Egypt", "", "0.99", "ce1126", "000000", "ffffff", "", "", "", "", "", "", "", "Egypt", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.equatorialguinea", "National Soccer", "Equatorial Guinea", "", "0.99", "e32118", "ffffff", "", "", "", "", "", "", "", "", "Equatorial Guinea", "", "", "6_4", "", ""],
        ["com.flashforceapp.eritrea", "National Soccer", "Eritrea", "", "0.99", "4189dd", "ea0437", "12ad2b", "", "", "", "", "", "", "", "Eritrea", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.ethiopia", "National Soccer", "Ethiopia", "", "0.99", "078930", "fcdd09", "da121a", "", "", "", "", "", "", "", "Ethiopia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.gabon", "National Soccer", "Gabon", "", "0.99", "fcd116", "3a75c4", "", "", "", "", "", "", "", "", "Gabon", "", "", "6_4", "", ""],
        ["com.flashforceapp.gambia", "National Soccer", "Gambia", "", "0.99", "ce1126", "0c1c8c", "3a7728", "", "", "", "", "", "", "", "Gambia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.ghana", "National Soccer", "Ghana", "", "0.99", "ffffff", "ce1126", "fcd116", "006b3f", "000000", "", "", "", "", "", "Ghana", "", "", "6_4_2_2_2", "", ""],
        ["com.flashforceapp.guinea", "National Soccer", "Guinea", "", "0.99", "ce1126", "fcd116", "009e49", "", "", "", "", "", "", "", "Guinea", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.guinea-bissau", "National Soccer", "Guinea-Bissau", "", "0.99", "ce1126", "fcd116", "009e49", "", "", "", "", "", "", "", "Guinea-Bissau", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.ivorycoast", "National Soccer", "Ivory Coast", "", "0.99", "f77f00", "009e60", "", "", "", "", "", "", "", "", "Ivory Coast", "", "", "6_4", "", ""],
        ["com.flashforceapp.kenya", "National Soccer", "Kenya", "", "0.99", "bb0000", "ffffff", "", "", "", "", "", "", "", "", "Kenya", "", "", "6_4", "", ""],
        ["com.flashforceapp.lesotho", "National Soccer", "Lesotho", "", "0.99", "00209f", "009543", "ffffff", "", "", "", "", "", "", "", "Lesotho", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.liberia", "National Soccer", "Liberia", "", "0.99", "bf0a30", "ffffff", "002868", "", "", "", "", "", "", "", "Liberia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.libya", "National Soccer", "Libya", "", "0.99", "ff0000", "000000", "ffffff", "", "", "", "", "", "", "", "Libya", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.madagascar", "National Soccer", "Madagascar", "", "0.99", "007e3a", "ffffff", "", "", "", "", "", "", "", "", "Madagascar", "", "", "6_4", "", ""],
        ["com.flashforceapp.malawi", "National Soccer", "Malawi", "", "0.99", "ce1126", "ffffff", "339e35", "", "", "", "", "", "", "", "Malawi", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.mali", "National Soccer", "Mali", "", "0.99", "fcd116", "ce1126", "14b53a", "", "", "", "", "", "", "", "Mali", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.mauritania", "National Soccer", "Mauritania", "", "0.99", "006233", "ffc400", "", "", "", "", "", "", "", "", "Mauritania", "", "", "6_4", "", ""],
        ["com.flashforceapp.mauritius", "National Soccer", "Mauritius", "", "0.99", "ffffff", "ea2839", "", "", "", "", "", "", "", "", "Mauritius", "", "", "6_4", "", ""],
        ["com.flashforceapp.morocco", "National Soccer", "Morocco", "", "0.99", "c1272d", "006233", "", "", "", "", "", "", "", "", "Morocco", "", "", "6_4", "", ""],
        ["com.flashforceapp.mozambique", "National Soccer", "Mozambique", "", "0.99", "D21034", "000000", "", "", "", "", "", "", "", "", "Mozambique", "", "", "6_4", "", ""],
        ["com.flashforceapp.namibia", "National Soccer", "Namibia", "", "0.99", "D21034", "ffffff", "", "", "", "", "", "", "", "", "Namibia", "", "", "6_4", "", ""],
        ["com.flashforceapp.niger", "National Soccer", "Niger", "", "0.99", "ffffff", "E05206", "0DB02B", "", "", "", "", "", "", "", "Niger", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.nigeria", "National Soccer", "Nigeria", "", "0.99", "008751", "ffffff", "", "", "", "", "", "", "", "", "Nigeria", "", "", "6_4", "", ""],
        ["com.flashforceapp.reunion", "National Soccer", "Reunion", "", "0.99", "008000", "ff0000", "", "", "", "", "", "", "", "", "Reunion", "", "", "6_4", "", ""],
        ["com.flashforceapp.rwanda", "National Soccer", "Rwanda", "", "0.99", "fad201", "20603d", "00a1de", "", "", "", "", "", "", "", "Rwanda", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.saotomeandprincipe", "National Soccer", "Sao Tome and Principe", "", "0.99", "12ad2b", "d21034", "000000", "", "", "", "", "", "", "", "Sao Tome and Principe", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.senegal", "National Soccer", "Senegal", "", "0.99", "fcd856", "d62828", "007a3d", "", "", "", "", "", "", "", "Senegal", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.seychelles", "National Soccer", "Seychelles", "", "0.99", "ffffff", "d62828", "", "", "", "", "", "", "", "", "Seychelles", "", "", "6_4", "", ""],
        ["com.flashforceapp.sierraleone", "National Soccer", "Sierra Leone", "", "0.99", "1eb53a", "0072c6", "", "", "", "", "", "", "", "", "Sierra Leone", "", "", "6_4", "", ""],
        ["com.flashforceapp.somalia", "National Soccer", "Somalia", "", "0.99", "4189dd", "ffffff", "", "", "", "", "", "", "", "", "Somalia", "", "", "6_4", "", ""],
        ["com.flashforceapp.southafrica", "National Soccer", "South Africa", "", "0.99", "ffb612", "007a4d", "", "", "", "", "", "", "", "", "South Africa", "", "", "6_4", "", ""],
        ["com.flashforceapp.southsudan", "National Soccer", "South Sudan", "", "0.99", "ffffff", "0f47af", "", "", "", "", "", "", "", "", "South Sudan", "", "", "6_4", "", ""],
        ["com.flashforceapp.sudan", "National Soccer", "Sudan", "", "0.99", "d21034", "ffffff", "", "", "", "", "", "", "", "", "Sudan", "", "", "6_4", "", ""],
        ["com.flashforceapp.swaziland", "National Soccer", "Swaziland", "", "0.99", "3e5eb9", "ffd900", "", "", "", "", "", "", "", "", "Swaziland", "", "", "6_4", "", ""],
        ["com.flashforceapp.tanzania", "National Soccer", "Tanzania", "", "0.99", "3f60cb", "000000", "1eb53a", "", "", "", "", "", "", "", "Tanzania", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.togo", "National Soccer", "Togo", "", "0.99", "ffce00", "006a4e", "", "", "", "", "", "", "", "", "Togo", "", "", "6_4", "", ""],
        ["com.flashforceapp.tunisia", "National Soccer", "Tunisia", "", "0.99", "ffffff", "e70013", "", "", "", "", "", "", "", "", "Tunisia", "", "", "6_4", "", ""],
        ["com.flashforceapp.uganda", "National Soccer", "Uganda", "", "0.99", "fcdc04", "000000", "", "", "", "", "", "", "", "", "Uganda", "", "", "6_4", "", ""],
        ["com.flashforceapp.zambia", "National Soccer", "Zambia", "", "0.99", "198a00", "ef7d00", "000000", "", "", "", "", "", "", "", "Zambia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.zanzibar", "National Soccer", "Zanzibar", "", "0.99", "1eb53a", "ffffff", "", "", "", "", "", "", "", "", "Zanzibar", "", "", "6_4", "", ""],
        ["com.flashforceapp.zimbabwe", "National Soccer", "Zimbabwe", "", "0.99", "ffd200", "319208", "", "", "", "", "", "", "", "", "Zimbabwe", "", "", "6", "", ""],
        ["com.flashforceapp.anguilla", "National Soccer", "Anguilla", "", "0.99", "ff9900", "ffffff", "", "", "", "", "", "", "", "", "Anguilla", "", "", "6_4", "", ""],
        ["com.flashforceapp.antiguaandbarbuda", "National Soccer", "Antigua and Barbuda", "", "0.99", "fcd116", "000000", "0072c6", "ce1126", "", "", "", "", "", "", "Antigua and Barbuda", "", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.aruba", "National Soccer", "Aruba", "", "0.99", "f9d616", "4189dd", "", "", "", "", "", "", "", "", "Aruba", "", "", "6_4", "", ""],
        ["com.flashforceapp.bahamas", "National Soccer", "Bahamas", "", "0.99", "fae042", "000000", "00abc9", "", "", "", "", "", "", "", "Bahamas", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.barbados", "National Soccer", "Barbados", "", "0.99", "ffc726", "00267f", "", "", "", "", "", "", "", "", "Barbados", "", "", "6_4", "", ""],
        ["com.flashforceapp.belize", "National Soccer", "Belize", "", "0.99", "003f87", "ce1126", "ffffff", "", "", "", "", "", "", "", "Belize", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.bermuda", "National Soccer", "Bermuda", "", "0.99", "cf142b", "ffffff", "", "", "", "", "", "", "", "", "Bermuda", "", "", "6_4", "", ""],
        ["com.flashforceapp.bonaire", "National Soccer", "Bonaire", "", "0.99", "f9d90f", "012a87", "", "", "", "", "", "", "", "", "Bonaire", "", "", "6_4", "", ""],
        ["com.flashforceapp.britishvirginislands", "National Soccer", "British Virgin Islands", "", "0.99", "006129", "f7c600", "", "", "", "", "", "", "", "", "British Virgin Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.canada", "National Soccer", "Canada", "", "0.99", "ff0000", "ffffff", "000000", "", "", "", "", "", "", "", "Canada", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.caymanislands", "National Soccer", "Cayman Islands", "", "0.99", "ffffff", "cf142b", "", "", "", "", "", "", "", "", "Cayman Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.costarica", "National Soccer", "Costa Rica", "", "0.99", "ce1126", "002b7f", "", "", "", "", "", "", "", "", "Costa Rica", "", "", "6_4", "", ""],
        ["com.flashforceapp.cuba", "National Soccer", "Cuba", "", "0.99", "cf142b", "ffffff", "002a8f", "", "", "", "", "", "", "", "Cuba", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.curacao", "National Soccer", "Curacao", "", "0.99", "002b7f", "f9e814", "ffffff", "", "", "", "", "", "", "", "Curacao", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.dominica", "National Soccer", "Dominica", "", "0.99", "006b3f", "fcd116", "000000", "", "", "", "", "", "", "", "Dominica", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.dominicanrepublic", "National Soccer", "Dominican Republic", "", "0.99", "002d62", "ffffff", "", "", "", "", "", "", "", "", "Dominican Republic", "", "", "6_4", "", ""],
        ["com.flashforceapp.elsalvador", "National Soccer", "El Salvador", "", "0.99", "0f47af", "ffffff", "", "", "", "", "", "", "", "", "El Salvador", "", "", "6_4", "", ""],
        ["com.flashforceapp.frenchguiana", "National Soccer", "French Guiana", "", "0.99", "fcdd09", "002395", "078930", "da121a", "", "", "", "", "", "", "French Guiana", "", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.grenada", "National Soccer", "Grenada", "", "0.99", "fcd116", "007a5e", "", "", "", "", "", "", "", "", "Grenada", "", "", "6_4", "", ""],
        ["com.flashforceapp.guadeloupe", "National Soccer", "Guadeloupe", "", "0.99", "3e6107", "da121a", "", "", "", "", "", "", "", "", "Guadeloupe", "", "", "6_4", "", ""],
        ["com.flashforceapp.guatemala", "National Soccer", "Guatemala", "", "0.99", "4997d0", "ffffff", "", "", "", "", "", "", "", "", "Guatemala", "", "", "6_4", "", ""],
        ["com.flashforceapp.guyana", "National Soccer", "Guyana", "", "0.99", "009e49", "ffffff", "", "", "", "", "", "", "", "", "Guyana", "", "", "6_4", "", ""],
        ["com.flashforceapp.haiti", "National Soccer", "Haiti", "", "0.99", "00209f", "d21034", "", "", "", "", "", "", "", "", "Haiti", "", "", "6_4", "", ""],
        ["com.flashforceapp.honduras", "National Soccer", "Honduras", "", "0.99", "ffffff", "0073cf", "", "", "", "", "", "", "", "", "Honduras", "", "", "6_4", "", ""],
        ["com.flashforceapp.jamaica", "National Soccer", "Jamaica", "", "0.99", "fed100", "009b3a", "000000", "", "", "", "", "", "", "", "Jamaica", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.martinique", "National Soccer", "Martinique", "", "0.99", "ffffff", "21428e", "", "", "", "", "", "", "", "", "Martinique", "", "", "6_4", "", ""],
        ["com.flashforceapp.mexico", "National Soccer", "Mexico", "", "0.99", "006847", "ffffff", "ce1126", "", "", "", "", "", "", "", "Mexico", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.montserrat", "National Soccer", "Montserrat", "", "0.99", "000000", "cf142b", "", "", "", "", "", "", "", "", "Montserrat", "", "", "6_4", "", ""],
        ["com.flashforceapp.nicaragua", "National Soccer", "Nicaragua", "", "0.99", "0067C6", "000000", "", "", "", "", "", "", "", "", "Nicaragua", "", "", "6_4", "", ""],
        ["com.flashforceapp.panama", "National Soccer", "Panama", "", "0.99", "d21034", "ffffff", "", "", "", "", "", "", "", "", "Panama", "", "", "6_4", "", ""],
        ["com.flashforceapp.puertorico", "National Soccer", "Puerto Rico", "", "0.99", "ed0000", "ffffff", "0050f0", "", "", "", "", "", "", "", "Puerto Rico", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.saintkittsandnevis", "National Soccer", "Saint Kitts and Nevis", "", "0.99", "ce1126", "ffffff", "", "", "", "", "", "", "", "", "Saint Kitts and Nevis", "", "", "6_4", "", ""],
        ["com.flashforceapp.saintlucia", "National Soccer", "Saint Lucia", "", "0.99", "fcd116", "000000", "66ccff", "", "", "", "", "", "", "", "Saint Lucia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.saint-martin", "National Soccer", "Saint-Martin", "", "0.99", "ffffff", "ed2939", "", "", "", "", "", "", "", "", "Saint-Martin", "", "", "6_4", "", ""],
        ["com.flashforceapp.saintvincentandthegrenadines", "National Soccer", "Saint Vincent and the Grenadines", "", "0.99", "fcd116", "009e60", "0072c6", "", "", "", "", "", "", "", "Saint Vincent and the Grenadines", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.sintmaarten", "National Soccer", "Sint Maarten", "", "0.99", "012a87", "dc171d", "", "", "", "", "", "", "", "", "Sint Maarten", "", "", "6_4", "", ""],
        ["com.flashforceapp.suriname", "National Soccer", "Suriname", "", "0.99", "ffffff", "377e3f", "b40a2d", "", "", "", "", "", "", "", "Suriname", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.trinidadandtobago", "National Soccer", "Trinidad and Tobago", "", "0.99", "ce1126", "000000", "ffffff", "", "", "", "", "", "", "", "Trinidad and Tobago", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.turksandcaicosislands", "National Soccer", "Turks and Caicos Islands", "", "0.99", "00247d", "ffffff", "", "", "", "", "", "", "", "", "Turks and Caicos Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.usvirginislands", "National Soccer", "US Virgin Islands", "", "0.99", "0081c6", "f4c53d", "", "", "", "", "", "", "", "", "US Virgin Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.usa", "National Soccer", "USA", "", "0.99", "bf0a30", "ffffff", "002868", "", "", "", "", "", "", "", "USA", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.argentina", "National Soccer", "Argentina", "", "0.99", "74acdf", "ffffff", "", "", "", "", "", "", "", "", "Argentina", "", "", "6_4", "", ""],
        ["com.flashforceapp.bolivia", "National Soccer", "Bolivia", "", "0.99", "007934", "ffffff", "d52b1e", "ffe000", "", "", "", "", "", "", "Bolivia", "", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.brazil", "National Soccer", "Brazil", "", "0.99", "fedf00", "002776", "ffffff", "009b3a", "", "", "", "", "", "", "Brazil", "", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.chile", "National Soccer", "Chile", "", "0.99", "d52b1e", "0039a6", "ffffff", "", "", "", "", "", "", "", "Chile", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.colombia", "National Soccer", "Colombia", "", "0.99", "fcd116", "000000", "ce1126", "", "", "", "", "", "", "", "Colombia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.ecuador", "National Soccer", "Ecuador", "", "0.99", "ffdd00", "034ea2", "ed1c24", "", "", "", "", "", "", "", "Ecuador", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.paraguay", "National Soccer", "Paraguay", "", "0.99", "ffffff", "ce1126", "0038a8", "", "", "", "", "", "", "", "Paraguay", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.peru", "National Soccer", "Peru", "", "0.99", "ffffff", "d91023", "", "", "", "", "", "", "", "", "Peru", "", "", "6_4", "", ""],
        ["com.flashforceapp.uruguay", "National Soccer", "Uruguay", "", "0.99", "799fcc", "000000", "", "", "", "", "", "", "", "", "Uruguay", "", "", "6_4", "", ""],
        ["com.flashforceapp.venezuela", "National Soccer", "Venezuela", "", "0.99", "cf142b", "ffffff", "", "", "", "", "", "", "", "", "Venezuela", "", "", "6_4", "", ""],
        ["com.flashforceapp.americansamoa", "National Soccer", "American Samoa", "", "0.99", "ffffff", "ce1126", "002b7f", "", "", "", "", "", "", "", "American Samoa", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.cookislands", "National Soccer", "Cook Islands", "", "0.99", "00923f", "ffffff", "", "", "", "", "", "", "", "", "Cook Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.fiji", "National Soccer", "Fiji", "", "0.99", "ffffff", "000000", "", "", "", "", "", "", "", "", "Fiji", "", "", "6_4", "", ""],
        ["com.flashforceapp.kiribati", "National Soccer", "Kiribati", "", "0.99", "ce1126", "003f87", "fcd116", "", "", "", "", "", "", "", "Kiribati", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.newcaledonia", "National Soccer", "New  Caledonia", "", "0.99", "ED4135", "ffffff", "", "", "", "", "", "", "", "", "New  Caledonia", "", "", "6_4", "", ""],
        ["com.flashforceapp.newzealand", "National Soccer", "New Zealand", "", "0.99", "ffffff", "000000", "", "", "", "", "", "", "", "", "New Zealand", "", "", "6_4", "", ""],
        ["com.flashforceapp.niue", "National Soccer", "Niue", "", "0.99", "F7E017", "008000", "", "", "", "", "", "", "", "", "Niue", "", "", "6_4", "", ""],
        ["com.flashforceapp.papuanewguinea", "National Soccer", "Papua New Guinea", "", "0.99", "ce1126", "ffffff", "000000", "fcd116", "", "", "", "", "", "", "Papua New Guinea", "", "", "6_4_2_2", "", ""],
        ["com.flashforceapp.samoa", "National Soccer", "Samoa", "", "0.99", "002B7F", "ffffff", "", "", "", "", "", "", "", "", "Samoa", "", "", "6_4", "", ""],
        ["com.flashforceapp.solomonislands", "National Soccer", "Solomon Islands", "", "0.99", "fcd116", "215b33", "0051ba", "", "", "", "", "", "", "", "Solomon Islands", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.tahiti", "National Soccer", "Tahiti", "", "0.99", "ffffff", "ce1126", "", "", "", "", "", "", "", "", "Tahiti", "", "", "6_4", "", ""],
        ["com.flashforceapp.tonga", "National Soccer", "Tonga", "", "0.99", "ffffff", "c10000", "", "", "", "", "", "", "", "", "Tonga", "", "", "6_4", "", ""],
        ["com.flashforceapp.tuvalu", "National Soccer", "Tuvalu", "", "0.99", "5b97b1", "ffce00", "ffffff", "", "", "", "", "", "", "", "Tuvalu", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.vanuatu", "National Soccer", "Vanuatu", "", "0.99", "fdce12", "d21034", "009543", "", "", "", "", "", "", "", "Vanuatu", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.albania", "National Soccer", "Albania", "", "0.99", "e41e20", "000000", "ffffff", "", "", "", "", "", "", "", "Albania", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.andorra", "National Soccer", "Andorra", "", "0.99", "d0103a", "fedf00", "0018a8", "", "", "", "", "", "", "", "Andorra", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.armenia", "National Soccer", "Armenia", "", "0.99", "d90012", "ffffff", "", "", "", "", "", "", "", "", "Armenia", "", "", "6_4", "", ""],
        ["com.flashforceapp.austria", "National Soccer", "Austria", "", "0.99", "ed2939", "ffffff", "", "", "", "", "", "", "", "", "Austria", "", "", "6_4", "", ""],
        ["com.flashforceapp.azerbaijan", "National Soccer", "Azerbaijan", "", "0.99", "e00034", "0098c3", "00ae65", "", "", "", "", "", "", "", "Azerbaijan", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.belarus", "National Soccer", "Belarus", "", "0.99", "c8313e", "ffffff", "", "", "", "", "", "", "", "", "Belarus", "", "", "6_4", "", ""],
        ["com.flashforceapp.belgium", "National Soccer", "Belgium", "", "0.99", "ed2939", "ffffff", "", "", "", "", "", "", "", "", "Belgium", "", "", "6_4", "", ""],
        ["com.flashforceapp.bosnia-herzegovina", "National Soccer", "Bosnia-Herzegovina", "", "0.99", "002395", "ffffff", "", "", "", "", "", "", "", "", "Bosnia-Herzegovina", "", "", "6_4", "", ""],
        ["com.flashforceapp.bulgaria", "National Soccer", "Bulgaria", "", "0.99", "ffffff", "00966e", "d62612", "", "", "", "", "", "", "", "Bulgaria", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.croatia", "National Soccer", "Croatia", "", "0.99", "ff0000", "ffffff", "171796", "", "", "", "", "", "", "", "Croatia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.cyprus", "National Soccer", "Cyprus", "", "0.99", "002868", "ffffff", "", "", "", "", "", "", "", "", "Cyprus", "", "", "6_4", "", ""],
        ["com.flashforceapp.czechrepublic", "National Soccer", "Czech Republic", "", "0.99", "d7141a", "11457e", "", "", "", "", "", "", "", "", "Czech Republic", "", "", "6_4", "", ""],
        ["com.flashforceapp.denmark", "National Soccer", "Denmark", "", "0.99", "ce0000", "ffffff", "", "", "", "", "", "", "", "", "Denmark", "", "", "6_4", "", ""],
        ["com.flashforceapp.england", "National Soccer", "England", "", "0.99", "ffffff", "ce1124", "", "", "", "", "", "", "", "", "England", "", "", "6_4", "", ""],
        ["com.flashforceapp.estonia", "National Soccer", "Estonia", "", "0.99", "4891d9", "000000", "ffffff", "", "", "", "", "", "", "", "Estonia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.faroeislands", "National Soccer", "Faroe Islands", "", "0.99", "ffffff", "0065bd", "", "", "", "", "", "", "", "", "Faroe Islands", "", "", "6_4", "", ""],
        ["com.flashforceapp.finland", "National Soccer", "Finland", "", "0.99", "ffffff", "003580", "", "", "", "", "", "", "", "", "Finland", "", "", "6_4", "", ""],
        ["com.flashforceapp.france", "National Soccer", "France", "", "0.99", "002395", "ffffff", "ed2939", "", "", "", "", "", "", "", "France", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.fyrmacedonia", "National Soccer", "FYR Macedonia", "", "0.99", "d20000", "ffe600", "", "", "", "", "", "", "", "", "FYR Macedonia", "", "", "6_4", "", ""],
        ["com.flashforceapp.georgia", "National Soccer", "Georgia", "", "0.99", "ffffff", "ff0000", "", "", "", "", "", "", "", "", "Georgia", "", "", "6_4", "", ""],
        ["com.flashforceapp.germany", "National Soccer", "Germany", "", "0.99", "ffffff", "dd0000", "000000", "", "", "", "", "", "", "", "Germany", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.gibraltar", "National Soccer", "Gibraltar", "", "0.99", "da000c", "ffffff", "", "", "", "", "", "", "", "", "Gibraltar", "", "", "6_4", "", ""],
        ["com.flashforceapp.greece", "National Soccer", "Greece", "", "0.99", "ffffff", "0d5eaf", "", "", "", "", "", "", "", "", "Greece", "", "", "6_4", "", ""],
        ["com.flashforceapp.hungary", "National Soccer", "Hungary", "", "0.99", "cd2a3e", "ffffff", "436f4d", "", "", "", "", "", "", "", "Hungary", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.iceland", "National Soccer", "Iceland", "", "0.99", "003897", "D72828", "ffffff", "", "", "", "", "", "", "", "Iceland", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.israel", "National Soccer", "Israel", "", "0.99", "0038b8", "ffffff", "", "", "", "", "", "", "", "", "Israel", "", "", "6_4", "", ""],
        ["com.flashforceapp.italy", "National Soccer", "Italy", "", "0.99", "18B9F8", "ffffff", "", "", "", "", "", "", "", "", "Italy", "", "", "6_4", "", ""],
        ["com.flashforceapp.kazakhstan", "National Soccer", "Kazakhstan", "", "0.99", "fec50c", "00afca", "", "", "", "", "", "", "", "", "Kazakhstan", "", "", "6_4", "", ""],
        ["com.flashforceapp.latvia", "National Soccer", "Latvia", "", "0.99", "9e3039", "ffffff", "", "", "", "", "", "", "", "", "Latvia", "", "", "6_4", "", ""],
        ["com.flashforceapp.liechtenstein", "National Soccer", "Liechtenstein", "", "0.99", "002b7f", "ce1126", "", "", "", "", "", "", "", "", "Liechtenstein", "", "", "6_4", "", ""],
        ["com.flashforceapp.lithuania", "National Soccer", "Lithuania", "", "0.99", "fdb913", "006a44", "", "", "", "", "", "", "", "", "Lithuania", "", "", "6_4", "", ""],
        ["com.flashforceapp.luxembourg", "National Soccer", "Luxembourg", "", "0.99", "ffffff", "00a1de", "", "", "", "", "", "", "", "", "Luxembourg", "", "", "6_4", "", ""],
        ["com.flashforceapp.malta", "National Soccer", "Malta", "", "0.99", "cf142b", "ffffff", "", "", "", "", "", "", "", "", "Malta", "", "", "6_4", "", ""],
        ["com.flashforceapp.moldova", "National Soccer", "Moldova", "", "0.99", "0046ae", "ffd200", "", "", "", "", "", "", "", "", "Moldova", "", "", "6_4", "", ""],
        ["com.flashforceapp.montenegro", "National Soccer", "Montenegro", "", "0.99", "c40308", "d4af3a", "", "", "", "", "", "", "", "", "Montenegro", "", "", "6_4", "", ""],
        ["com.flashforceapp.netherlands", "National Soccer", "Netherlands", "", "0.99", "FF8400", "ffffff", "", "", "", "", "", "", "", "", "Netherlands", "", "", "6_4", "", ""],
        ["com.flashforceapp.northernireland", "National Soccer", "Northern Ireland", "", "0.99", "0b8f47", "ffffff", "", "", "", "", "", "", "", "", "Northern Ireland", "", "", "6_4", "", ""],
        ["com.flashforceapp.norway", "National Soccer", "Norway", "", "0.99", "ef2b2d", "ffffff", "002868", "", "", "", "", "", "", "", "Norway", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.poland", "National Soccer", "Poland", "", "0.99", "ffffff", "dc143c", "", "", "", "", "", "", "", "", "Poland", "", "", "6_4", "", ""],
        ["com.flashforceapp.portugal", "National Soccer", "Portugal", "", "0.99", "7D0013", "FF0000", "", "", "", "", "", "", "", "", "Portugal", "", "", "6_4", "", ""],
        ["com.flashforceapp.republicofireland", "National Soccer", "Republic of Ireland", "", "0.99", "009b48", "ffffff", "", "", "", "", "", "", "", "", "Republic of Ireland", "", "", "6_4", "", ""],
        ["com.flashforceapp.romania", "National Soccer", "Romania", "", "0.99", "fcd116", "ce1126", "", "", "", "", "", "", "", "", "Romania", "", "", "6_4", "", ""],
        ["com.flashforceapp.russia", "National Soccer", "Russia", "", "0.99", "e8112d", "ffffff", "1199ff", "", "", "", "", "", "", "", "Russia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.sanmarino", "National Soccer", "San Marino", "", "0.99", "5eb6e4", "ffffff", "", "", "", "", "", "", "", "", "San Marino", "", "", "6_4", "", ""],
        ["com.flashforceapp.scotland", "National Soccer", "Scotland", "", "0.99", "0065bd", "ffffff", "", "", "", "", "", "", "", "", "Scotland", "", "", "6_4", "", ""],
        ["com.flashforceapp.serbia", "National Soccer", "Serbia", "", "0.99", "c6363c", "0c4076", "ffffff", "", "", "", "", "", "", "", "Serbia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.slovakia", "National Soccer", "Slovakia", "", "0.99", "ffffff", "0b4ea2", "ee1c25", "", "", "", "", "", "", "", "Slovakia", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.slovenia", "National Soccer", "Slovenia", "", "0.99", "ffffff", "005da4", "", "", "", "", "", "", "", "", "Slovenia", "", "", "6_4", "", ""],
        ["com.flashforceapp.spain", "National Soccer", "Spain", "", "0.99", "da121a", "fcdd09", "0071bc", "", "", "", "", "", "", "", "Spain", "", "", "6_4_2", "", ""],
        ["com.flashforceapp.sweden", "National Soccer", "Sweden", "", "0.99", "006aa7", "fecc00", "", "", "", "", "", "", "", "", "Sweden", "", "", "6_4", "", ""],
        ["com.flashforceapp.switzerland", "National Soccer", "Switzerland", "", "0.99", "d52b1e", "ffffff", "", "", "", "", "", "", "", "", "Switzerland", "", "", "6_4", "", ""],
        ["com.flashforceapp.turkey", "National Soccer", "Turkey", "", "0.99", "e30a17", "ffffff", "", "", "", "", "", "", "", "", "Turkey", "", "", "6_4", "", ""],
        ["com.flashforceapp.ukraine", "National Soccer", "Ukraine", "", "0.99", "005bbb", "ffd500", "", "", "", "", "", "", "", "", "Ukraine", "", "", "6_4", "", ""],
        ["com.flashforceapp.wales", "National Soccer", "Wales", "", "0.99", "d21034", "ffcc00", "00ab39", "", "", "", "", "", "", "", "Wales", "", "", "6_4_2", "", ""],
    ]
    
}